kiegroup/kie-ci

job-dsls/jobs/downstream_pr_jobs.groovy

@mbiarnes please take a look whenever you have some time

[DROOLS-1521] Add DSL script for downstream PR jobs

---

job-dsls/jobs/deploy_jobs.groovy

Send uberfire notifications to #appformer channel

---

job-dsls/jobs/downstream_pr_jobs.groovy

@mbiarnes please approve
cc @hasys

Increase downstream build timeout to 5 hours

---

job-dsls/jobs/kie_release_jobs.groovy

please merge this after we have tagged community 7.1.0.Final

fixed uberfire and dashbuilder paths

---

job-dsls/jobs/FlowJob.groovy

@psiroky all these changes are also done on jobs on Jenkins CI - so for this PR there is no hurry.
I disabled the Trigger All job - so we have don't have executed twice a day the kie all build on master.
I also need to add one/two test:
kie-all-build-windows-master 
kie-all-build-master-mvn339 (I think this is was for testing MAVEN 3_3_9 and we don't need it)

changed versions for master branches & fixed job name

---

job-dsls/jobs/downstream_pr_jobs.groovy

@mbiares please take a look.
CC @hasys

Archive kie-server WARs in downstream PR builds

---

job-dsls/jobs/pr_jobs.groovy

Fix archive patterns for kie-wb WARs

---

job-dsls/jobs/FlowJob.groovy
job-dsls/jobs/kie_release_jobs.groovy

removed also leftover in job-dsls/jobs/kie_release_jobs.groovy - def pushReleaseBranches=""" ... """" since this is in scripts droolsjbpm-build-bootstrap/script/release/kie-createAndPushReleaseBranches.sh

Upgrade maven master

---

job-dsls/jobs/FlowJob.groovy

* no need to clone into subdir (only complicates things)

Fix kie-docker-ci-images DSL

---

job-dsls/build.gradle
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Backport of #66. @mbiarnes please review.

[6.5.x] freestyle deploy jobs + ws cleanup

---

job-dsls/jobs/deploy_jobs.groovy

Backport of #66.
@mbiarnes please review.

[#64] use Freestyle job type for deploy jobs

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Needs to be merged after https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/549

[#74] add deploy and PR jobs for kie-soup repo

---

job-dsls/jobs/FlowJob.groovy

@psiroky makes only sense if https://github.com/kiegroup/kie-soup/pull/2 was merged

added kie-soup to dailyBuilds jobs

---

job-dsls/jobs/FlowJob.groovy

to work properly there is another PR https://github.com/kiegroup/kie-soup/pull/4 that should be merged too in order to work on kie-daily-builds

updated script for kie-soup in daily builds

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Needed as a fix for https://issues.apache.org/jira/browse/MDEPLOY-221

Build with Maven 3.5.2

---

job-dsls/jobs/kie_release_jobs.groovy

DON'T MERGE. 
Merge together with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/610

added job for jbpm-installers

---

job-dsls/jobs/kie_release_jobs.groovy

- adapted job to work with new scripts

adapted to new and modyfied scripts

---

job-dsls/jobs/FlowJob.groovy

This is needed to save some disk space so that the builds would not fail
with "no space left on device".
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/613

kie-all: run clean-up script after each repo build

---

job-dsls/jobs/kie_release_jobs.groovy

forget to add this in a previous commit related to the jbpm-installer

added archive artifacts

---

job-dsls/jobs/FlowJob.groovy

@psiroky can you please merge (once green) - I want to do a test-release

removed jobs for kie-soup, uberfire and dashbuilder

---

job-dsls/jobs/FlowJob.groovy

finally - this works 
the build was done without he correct settings.xml and so the daily build failed.
now I am testing it and it works - it is building

added correct settings.xml

---

job-dsls/jobs/kie_release_jobs.groovy

removed obsolete jobs since appformer is in kie

fixed update-all-version.sh incl. kie-soup and appformer

---

job-dsls/jobs/FlowJob.groovy

Merge only after https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/637/files as this groovy file needs the updated update-versions-all.sh script which includes the version upgrade of appformer and kie-soup.

apdated to use new update-versions-all.sh script

---

job-dsls/jobs/kie_build_helper_jenkins_plugin_pr_job.groovy

Fix kiegroup/kie-build-helper-jenkins-plugin#16

Add kie-build-helper-jenkins-plugin PR job.

---

job-dsls/jobs/kie_build_helper_jenkins_plugin_pr_job.groovy

Fix kiegroup/kie-build-helper-jenkins-plugin#16

Fix github URL in kie-build-helper-jenkins-plugin

---

job-dsls/jobs/FlowJob.groovy
job-dsls/jobs/kie_release_jobs.groovy

(cherry picked from commit 1c7b28c9200451368e700291f98eebc3dc39b8bc)

updated to use EAP 7.1

---

job-dsls/jobs/zanataPull.groovy
job-dsls/jobs/zanataPush.groovy

new DSL for zanata push modules

added new script for Zanata push modules

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_release_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

@pszubiak the separated PRs were closed - here is one with three

Three commits

---

job-dsls/jobs/FlowJob.groovy

@pszubiak this has to be merged today since the errai version upgrade was merged yesterday in kie

upgraded errai version for daily builds

---

jenkins-slaves/ansible/kie-rhel7.yaml

New maven repository cache url.

---

jenkins-slaves/ansible/kie-rhel7.yaml

Remove duplicate appformer repository from git cache.

---

job-dsls/jobs/FlowJob.groovy

added a job for the prod daily build, it will archive an artifact prodBranches.tgz that contains all repsoitories (master branch) wich were used to do this build

added scrit for prod build

---

job-dsls/jobs/FlowJob.groovy

added missing trigger

---

job-dsls/jobs/FlowJob.groovy

the prodBuild will be triggered by the main trigger job

triggered the prod Build by main trigger job

---

jenkins-slaves/ansible/kie-rhel7.yaml

Adds jbpm-work-items repository to the git cache.

---

job-dsls/jobs/FlowJob.groovy

Update version of nexus-staging-maven-plugin to 1.6.8.

---

jenkins-slaves/ansible/kie-rhel7.yaml

Adds 8GB swap file.

---

job-dsls/jobs/FlowJob.groovy

New properties had to be added for creating the right versions for the prod build.

fixed prod Build, added parameters

---

job-dsls/jobs/FlowJob.groovy

(cherry picked from commit 4c2613d4db2a61e618729e56536cd982b9424b17)
it seems the **/TEST-*.xml in this tests works better

fixed paths to test results

---

job-dsls/jobs/kie_build_helper_jenkins_plugin_pr_job.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/BasicJob.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

Add template mechanism to DSL scripts to avoid code duplication.

---

job-dsls/jobs/pr_jobs.groovy

(cherry picked from commit 637e06c0ab57e024244244eb32f5bb7327b7f409)

changed order for PRs

---

job-dsls/jobs/FlowJob.groovy

(cherry picked from commit 9f9504024c5f498edfb6c53eb98d4711719cbdcb)

added save screenshots for selemiun failures

---

job-dsls/jobs/bxms_patch_tools_pr.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

jboss-integration/bxms-patch-tools#108

Adds PR verification job for bxms-patch-tools.

---

job-dsls/build.gradle
job-dsls/src/test/groovy/org/kie/jenkins/jobdsl/JobScriptsSpec.groovy
job-dsls/src/test/groovy/org/kie/jenkins/jobdsl/org/kie/jenkins/jobdsl/support/TestUtil.groovy

Adds pipelineJob test support.

---

job-dsls/build.gradle
job-dsls/src/test/groovy/org/kie/jenkins/jobdsl/JobScriptsSpec.groovy
job-dsls/src/test/groovy/org/kie/jenkins/jobdsl/org/kie/jenkins/jobdsl/support/TestUtil.groovy

(cherry picked from commit e865be217ead97bbafa05567e263c0a0f8aa6cad)

Adds pipelineJob test support. (#178)

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

(cherry picked from commit 9e40c4afb2e115f1ab1471f1121c8c432ac3d9a4)
lets tweak the pipeline job the next weeks

replaced Flow job by pipeline job

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/pr_jobs.groovy

Fix kie-wb-distributions oom error.

---

job-dsls/jobs/bxms_patch_tools_pr.groovy
job-dsls/jobs/kie_build_helper_jenkins_plugin_pr_job.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

Adds private repository support for PR verification jobs.

---

job-dsls/jobs/bxms_patch_tools_pr.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

PR verification jobs - change credentials name to id.

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

wrong job name caused a build failure in errai.

fixed to right jobname

---

job-dsls/jobs/deploy_jobs.groovy

(cherry picked from commit a35149934b41e33d6552d89d585927fb137b7d12)

new artifacts to archive in optashift-employee-rostering

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

(cherry picked from commit 47b3fc5c34f737ac7361517dfa7bb8361ed8f8a5)

added new profile and set new timer

---

job-dsls/jobs/pr_jobs.groovy

(cherry picked from commit bf2146f191961af7292aba591f6f3cbfe57ea2de)
added /target/configurations/cargo-profile/profile-log.txt to PR jobs

added new artifact to archive for PR jobs

---

job-dsls/jobs/zanataPull.groovy
job-dsls/jobs/zanataPush.groovy

scripts are needed for the upcoming RHDA 7.0.1

added script for Zanata translations

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

Change slave node label for kieAllBuild.

---

jenkins-slaves/ansible/kie-rhel7.yaml

Add zip package to slave nodes.

---

job-dsls/jobs/zanataPush.groovy

(cherry picked from commit 6c84305b2325203239df1924ae2dbf04111f97a2)

added variable for use of right branch

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/kie_dailyBuild_pipeline.groovy

applied all changes for "deploying" (upload a zip to QA Nexus)
- new settings.xml
- changed hard coded properties to use of variables
- adapted to higher firefox driver (as it is in other scripts) 
- use of credentialsBinding (so the user and pwd is not visible since stored on Jenkins)
- fixed label for errai build
- adjusted additional tests to grab the sources from the right URL
These changes are now for master only. Lets see if tomorrow everything builds properly and we will do these changes also to 7.7.x and 7.5.x.

Unpack qa nexus

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/kie_dailyBuild_pipeline.groovy

since kieAllBuild master builds with these changes they were backported to 7.7.x

Unpack qa nexus 7.7.x

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

since kieAllBuild master builds with these changes they were backported to 7.5.x

fit kieAllBuild 7.5.x to unpack to QA Nexus

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

aligned to a new errai branch 4.2.x and its SNAPSHOT

upgraded errai version to next SNAPSHOT

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Set cron trigger frequency for PR and blessed jobs to 20 minutes.

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_build_helper_jenkins_plugin_pr_job.groovy
job-dsls/jobs/pr_jobs.groovy

Set cron trigger frequency for PR and blessed jobs to 30 minutes.

---

job-dsls/jobs/downstream_pr_jobs.groovy

(cherry picked from commit 5eee7f7af4e0953f6dd667c41d10da9cd3cc4c7f)

added new profile for droolsjbpm-integration downstream

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

forget to fix the URL for errai

fixed errai unpack URL for 7.5.x

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

forget to fix the URL for errai

fixed errai unpack URL for 7.7.x

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

forget to fix the URL for errai

fixed errai unpack URL for master

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

changed absolute timeout to elastic timeout

---

job-dsls/jobs/bxms_patch_tools_pr.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

BXMSPROD-5 add GitHub token ID for PR verification jobs.

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_build_helper_jenkins_plugin_pr_job.groovy
job-dsls/jobs/pr_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

BXMSPROD-5 switch master branch builds to kiereleaseuser2.

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Disable verification jobs for 7.5.x branch.

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

BXMSPROD-5 switch 7.7.x branch builds to kiereleaseuser3.

---

job-dsls/jobs/bxms_patch_tools_pr.groovy
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie-docs-pr.groovy
job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kie_release_jobs.groovy
job-dsls/jobs/pr_jobs.groovy
job-dsls/jobs/zanataPull.groovy
job-dsls/jobs/zanataPush.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

BXMSPROD-17 change kie-docs PR verification job to standalone.

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

BXMSPROD-21 switch GitHub auth token to kiereleaseuser2.

---

job-dsls/jobs/bxms_patch_tools_pr.groovy
job-dsls/jobs/kie_build_helper_jenkins_plugin_pr_job.groovy
job-dsls/jobs/kie_docs_pr.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

BXMSPROD-21 adjust jobs generated from templates to rhba-jenkins.

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

BXMSPROD-21 enable template generated PR jobs.

---

job-dsls/jobs/pr_jobs.groovy

BXMSPROD-21 change folder configuration from absolute to relative.

---

job-dsls/jobs/pr_jobs.groovy

BXMSPROD-21 enable PR jobs.

---

job-dsls/jobs/downstream_pr_jobs.groovy

BXMSPROD-21 change folder configuration to relative for downstream jobs.

---

job-dsls/jobs/downstream_pr_jobs.groovy

BXMSPROD-21 enable dowstream PR jobs.

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

master pipeline executes at 22:00 h (CET) to prevent have building it until midday.

new build time for pipeline job

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Set kiereleaseuser3 token for 7.11.x branch.

---

job-dsls/jobs/kie_docs_pr.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

@mbiarnes @pszubiak would you mind to review?

BXMSPROD-69: Archive kie-docs artifacts

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

@mbiarnes I'm working on automating some analyses of console log of daily builds and I need to clean up some useless junk from the log to be able to extract data from it more effectively.
This PR removes the following useless lines from console log of daily build
and will make some analyses of the logs easier:
```
Checking out files:  34% (1692/4914)
Checking out files:  35% (1720/4914)
Checking out files:  36% (1770/4914)
Checking out files:  37% (1819/4914)
Checking out files:  38% (1868/4914)
Checking out files:  39% (1917/4914)
Checking out files:  40% (1966/4914)
Checking out files:  41% (2015/4914)
Checking out files:  42% (2064/4914)
Checking out files:  43% (2114/4914)
Checking out files:  44% (2163/4914)
Checking out files:  45% (2212/4914)
Checking out files:  46% (2261/4914) …
```

Don't show progress when cloning git repos and uploading build artifacts via curl

---

job-dsls/jobs/compile_downstream_build.groovy

for the compilation of all downstream reps skipping tests and skipping gwt compilation

added new groovy script

---

job-dsls/jobs/compile_downstream_build.groovy

@pszubiak can you please merge this once approved

fixed label names for kie Jenkins

---

jenkins-slaves/ansible/kie-rhel7.yml

BXMSPROD-121 fix typo.

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kie_release_jobs.groovy

@mareknovotny Cherry-picking eap7 version update from master as you suggested in https://github.com/kiegroup/kie-jenkins-scripts/pull/346

EAP 7 version update

---

job-dsls/jobs/compile_downstream_build.groovy

Change github message for compile downstream build.

---

job-dsls/jobs/compile_downstream_build.groovy

Change github message for compile downstream build. (#359)

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

need this merged so all PRs are updated to use this mvn version

upgraded Maven version

---

jenkins-slaves/ansible/roles/rhba/tasks/main.yml

Change import key task from shell to rpm_key module.

---

job-dsls/jobs/compile_downstream_build.groovy

BXMSPROD-171 execute compile downstream build for drools by default.

---

job-dsls/jobs/compile_downstream_build.groovy

Update Maven version for compile builds.

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

@pszubiak Please feel free to merge once it is green

adpated Constant.groovy for master

---

job-dsls/jobs/kie_release_jobs.groovy

Please merge this together with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/888/files
since this PR makes available a sh script needed in this PR

BXMSPROD-172: new script for branching and upgrading auxiliary repositories

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kie_release_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Bringing back the changes I had to revert last week now, that we have PM blessing.

AF-1511: consolidate kie-wb/kie-drools-wb into single business-central (#337)

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy

Fix disable of 7.11.x branch.

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

(cherry picked from commit d0bb7e9a50b0e9c1c3e20f4b0208df1be9f1dad0)

changed order in publisher {} - wsCleanup as last

---

jenkins-slaves/ansible/data/config/pulp/pulp.repo

Fix RHEL 7 repositories URLs.

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

BXMSPROD-246 change pulling interval to 20 minutes.

---

jenkins-slaves/ansible/data/config/pulp/pulp.repo
jenkins-slaves/packer-kie-rhel7.json

BXMSPROD-243 Adjust packer configuration to UpShift.

---

job-dsls/jobs/compile_downstream_build.groovy

Adjust compile downstream jobs to rhba-jenkins.

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

BXMSPROD-246 use different GitHub token for each job type.

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

@pszubiak @jomarko 
I hope the wars don't have another name in product?
**/target/business-central\*wildfly\*.war ?
**target/business-central\*eap\*.war ?
Can you check this please?

added prod artifacts to archive

---

jenkins-slaves/ansible/kie-rhel7.yml

Update JDKs 8 and 11.

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

BXMSPROD-246 add jq for json parsing.

---

job-dsls/jobs/github_api_limit.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

BXMSPROD-246 add monitor job for GitHub API limit.

---

job-dsls/jobs/github_api_limit.groovy

BXMSPROD-246 fix credential binding.

---

job-dsls/jobs/github_api_limit.groovy

* fix if statement,
* don't notify every unstable build.

BXMSPROD-246 multiple fixes.

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

BXMSPROD-246 change pulling interval to 5 minutes.

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

(cherry picked from commit 7e1646918d50f56977765e7ff0a26f088123496c)

no wifly14 war available for productization

---

job-dsls/jobs/pr_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

Increase pulling interval for PR veryfication jobs.

---

job-dsls/jobs/springboot_pr_job.groovy

Hi,
the Spring Boot job should be finished. Can you quickly check? @sutaakar especially the parameters, I left there also other parameters from normal PR jobs, although they may not be needed. But since https://github.com/kiegroup/droolsjbpm-integration/pull/1771 works, I would leave it now as is...
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1771

JBPM-8361- Create on-demand Spring Boot PR check

---

job-dsls/jobs/submarine.groovy

@mswiderski 
creates a four jobs 
pipeline job (for all submarine reps)
sumbarine-bom
submarine-runtimes
submarine-examples
you can see the jobs at
[sumbarine pipeline](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/submarine/job/submarine-pipeline-master/)
[submarine-bom](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/submarine/job/submarine-bom-master/)
[submarine-runtimes](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/submarine/job/submarine-runtimes-master/)
[submarine-examples](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/submarine/job/submarine-examples-master/)

added script for submarine pipeline and jobs

---

job-dsls/jobs/submarine.groovy

@mswiderski tested - works - there has also been done an additional fix to settings.xml on Jenkins

changed builds to deploy

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

@mbiarnes as we discussed, a follow-up to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/921

DROOLS-1781: replaces findbugs-maven-plugin

---

job-dsls/jobs/pr_jobs.groovy

@mbiarnes we missed one important `D` character :)
follow-up to https://github.com/kiegroup/kie-jenkins-scripts/pull/435

fix PR jobs for DROOLS-1781: replaces findbugs-maven-plugin

---

jenkins-slaves/ansible/roles/common/tasks/main.yml
jenkins-slaves/packer-kie-rhel7.json

Add packer to jenkins slave.

---

job-dsls/jobs/submarine_pr_jobs.groovy

this is a temporary solution until we change to Github Branch Source Plugin

added temp script for submarine-runtime PRs

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/BasicJob.groovy

Replaced Piotr with Alberto in our jobs definitions

Removing Piotr from coowners

---

job-dsls/jobs/kie_release_jobs.groovy

removes two superfluous release jobs (never used) and adds new params to a job needed for working with a script in droolsjbpm-build-bootstrap
will work only after https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/948 was merged

new params for one job nad removed two jobs

---

job-dsls/jobs/pr_jobs.groovy

SonarCloud analysis is about to because a part of PR checks. It already works for OptaPlanner, but so far the analysis ran in Travis, which showed to be infeasible solution due to various restrictions.
This PR enables SonarCloud analysis in Jenkins PR check jobs - so far only for OptaPlanner, but other repositories will follow.

Include SonarCloud analysis into OptaPlanner PR check job

---

job-dsls/jobs/seed_job.groovy

Created a job [seed-job](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/seed-job/) that creates automatically a seed job with all scripts to create needed jobs for a new branch.
This will work only if this PR is merged before branching the next time (==> 7.23.x).

BXMSPROD-387: added new script for seed job

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

@mbiarnes @mareknovotny 
I hope this fixes the overwriting of PR jobs. It is aligned with master.
https://github.com/kiegroup/kie-jenkins-scripts/blob/bb6c66b3166c9e9e91a940a83630d78db636567d/job-dsls/jobs/downstream_pr_jobs.groovy#L78-L79
https://github.com/kiegroup/kie-jenkins-scripts/blob/bb6c66b3166c9e9e91a940a83630d78db636567d/job-dsls/jobs/pr_jobs.groovy#L135-L136

[6.5.x] Distinguish between PR and full downstream PR jobs

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

https://issues.jboss.org/browse/BXMSPROD-403

fixing anonymous access to github API and jdk8 configuration

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

DROOLS-4147 
related new repository addition https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/968

DROOLS-4147 CI jobs for kie-jpmml-integration repo

---

job-dsls/jobs/kie_release_jobs.groovy

(cherry picked from commit 3348b5d62d651cf2f8dc95dd687e8d0286fb8661)

fixed custom workspace

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

Since the structure of directories in Jenkins-jobs changed the docker job is not found any more. A new variable is needed.

added new variable for the full path to docker script

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

(cherry picked from commit 71a55e5cf3a3c54ef2cd78827b51cc74998ae3ba)

added variable for branch in  UMB trigger

---

jenkins-slaves/packer-kie-rhel7.json
job-dsls/jobs/slave_image_build.groovy

Updated slave image build job DSL to avoid authentication issues when cloning from Gerrit.

BXMSPROD-401: fix slave image build job DSL

---

job-dsls/jobs/pr_jobs.groovy
job-dsls/jobs/sonarcloud_daily.groovy

Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/979

BAQE-1001 Unify reporting to SonarCloud under KIE parent

---

job-dsls/jobs/kie_jenkinsScripts_PR.groovy

creates a DSL groovy job for kie-jenkins-scripts PRs

BXMSPROD-399: new script for CI PR builder for kie-jenkins-scripts

---

job-dsls/jobs/seed_job.groovy

it will also take the new job kie_jenkinsScripts_PR.groovy

added all jobs starting with kie* to seed-job

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

@mareknovotny @jiripetrlik 
IMPORTANT: merge after
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/999
was merged

added pr and deploy job for openshift-drools-hacep

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

@winklerm @mbiarnes 
This should fix failures from this job - https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/kogito-tooling/view/change-requests/job/PR-7/

BXMSPROD-458: Add libXScrnSaver package

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

added optaweb-vehicle-routing to pr jobs and deployed jobs

added optaweb-vehicle-routing

---

job-dsls/jobs/pr_jobs.groovy
job-dsls/jobs/sonarcloud_daily.groovy

Depends on https://github.com/kiegroup/appformer/pull/711.

AF-1652 Enable sonarcloud for appformer - PR check and daily analysis

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

@winklerm changed the order also in kie-enkins-scripts files like https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/2799f60ab2cd90f3e922f963a8df6cda02ff166e

changed order in respositories

---

job-dsls/jobs/seed_job.groovy
job-dsls/jobs/turtleTests.groovy

- adds new DSL groovy scripts for drools and optaplanner turtle tests
- adds new script to seed job

added new script for turtle tests

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

changed the github user for 7.23.x branch to avoid reaching access limits

changed github users

---

jenkins-slaves/ansible/roles/kie/tasks/main.yml

@winklerm @mbiarnes Forgot to add step for copying the file

AF-2004: Add xstartup file creation step

---

job-dsls/jobs/pr_jobs.groovy
job-dsls/jobs/sonarcloud_daily.groovy

@rsynek @mbiarnes 
let me know if I am missing some parts

AF-2145: Introduce kie-soup to sonar with PR and daily checks

---

job-dsls/jobs/pr_jobs.groovy
job-dsls/jobs/sonarcloud_daily.groovy

@mbiarnes @rsynek 
See https://issues.jboss.org/browse/DROOLS-4434

[DROOLS-4434] Add drools-wb to sonar jobs

---

jenkins-slaves/ansible/roles/common/tasks/main.yml
jenkins-slaves/ansible/roles/kie/tasks/main.yml
jenkins-slaves/ansible/roles/rhba/tasks/main.yml

Replace yum task form which is now deprecated.

Avoid deprecated Ansible yum task form

---

job-dsls/jobs/sonarcloud_daily.groovy

@rsynek Can you please take a look?

Raise droolsjbpm-integration job timeout to 4 hours

---

job-dsls/build.gradle
job-dsls/gradle.properties
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/kie_jenkinsScripts_PR.groovy

Upgraded Jenkins to the more recent version, fix missing folder in test.

JobDSL: Upgrade Jenkins used in tests, fix unstable test

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kogito.groovy

Fixed the UMB trigger topic for 7.26.x.

Job DSL: update UMB triggers for 7.26.x

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kogito.groovy

Updated UMB selector to use already existing property.

jobDSL: update UMB selector to use existing property

---

job-dsls/jobs/pr_jobs.groovy

[DROOLS-4511] Fix drools-wb repository definition inside pr_jobs.groovy

---

job-dsls/jobs/kie_release_jobs.groovy

adds the new shell script for "prod" that removes the created release branches

BXMSPROD-524: added shell script for removing branches on Gerrit

---

job-dsls/jobs/pr_jobs.groovy

extended eMail notification for PRs on master (once this is working and people are OK with this, this will be cherry-picked to other PRs and to 7.26.x)

BXMSPROD-523: added extended email notification to PR jobs

---

job-dsls/jobs/pr_jobs.groovy

replaced email token $BUILD_LOG by $BUILD_LOG_REGEX and the lines to show in extended email notification

eMail token for reg expression

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kie_release_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

@mareknovotny when approved please merge

changed groovy script for not depending any more on uberfire version

---

job-dsls/jobs/kogito.groovy

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

fix dir typo

---

job-dsls/jobs/kogito.groovy

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

[KOGITO-258] - activate cekit virtualenv

---

job-dsls/jobs/kie_release_jobs.groovy

I forget to backport this one. We have this change only on master.

backported script for removing release branches on Gerrit

---

job-dsls/jobs/kogito.groovy

Signed-off-by: Filippe Spolti <fspolti@redhat.com>

[KOGITO-258] - Follow up, authenticate on registry

---

job-dsls/jobs/pr_jobs.groovy

(cherry picked from commit fc5132d1d09dca00e528cd30ff666b475b2cda12)

uses now provided settings

---

job-dsls/jobs/compile_downstream_build.groovy

(cherry picked from commit aef4f61259a307e2701c37952fd5d84680f411b7)

added custom settings.xml to compile downstream builds

---

job-dsls/jobs/downstream_pr_jobs.groovy

continuation of updating settings.xml for jira client dep.
see https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/droolsjbpm-build-bootstrap-downstream-pullrequests/92/consoleText

updated settings.xml for downstream build

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy

(cherry picked from commit fe2c836ed7875fa4a1bdbfb85603100ab06cd8b7)

added settings.xml for downstream and compile downstream builds

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy

@mareknovotny hopefully this will fix it.

Add settings.xml file to downstream and upstream goals

---

jenkins-slaves/ansible/roles/kie/tasks/main.yml

BXMSPROD-532 Remove "Download Maven repo cache" from kie-jenkins script

---

job-dsls/jobs/zanataPull.groovy
job-dsls/jobs/zanataPush.groovy

(cherry picked from commit 5cacd4e0e699fd6b75fe5730b8079deea121c611)

disabled Zanata jobs since Zanata server doesn't exist any more

---

job-dsls/jobs/pr_jobs.groovy

@rsynek @danielezonca 
Hi pls check, thx!

[DROOLS-4644] Fix drools-wb repository definition inside pr_jobs.groovy

---

job-dsls/build.gradle
job-dsls/jobs/DailyBuild_pipeline.groovy
job-dsls/jobs/DailyBuild_prod_pipeline.groovy
job-dsls/jobs/ProdTag_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

added steps for removing npm and yarn files
New groovy scripts for daily build pipelines and prod tag pipeline.
Tested locally.
Please merge together with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1074
(these sh scripts are needed)

added a new pipeline scripts for daily builds

---

job-dsls/jobs/DailyBuild_pipeline.groovy
job-dsls/jobs/DailyBuild_prod_pipeline.groovy
job-dsls/jobs/ProdTag_pipeline.groovy

New scripts and pipelines

---

job-dsls/jobs/DailyBuild_pipeline.groovy
job-dsls/jobs/DailyBuild_prod_pipeline.groovy

... this night both daily builds built. 
There are only small changes to add.

Daily build fixes

---

job-dsls/jobs/DailyBuild_pipeline.groovy

additional test results are also send to bsig list

changed email recipients of additional test

---

job-dsls/build.gradle
job-dsls/jobs/CommunityRelease_pipeline.groovy
job-dsls/jobs/DailyBuild_pipeline.groovy
job-dsls/jobs/DailyBuild_prod_pipeline.groovy
job-dsls/jobs/ProdTag_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

new pipelines (same as we did on master)

new pipelines for daily builds, product tags and community releases

---

job-dsls/jobs/ProdTag_pipeline.groovy

(cherry picked from commit a5280ca7a3c2114c01644b272e837ba96d3a2f6c)

removed stage of removing yarn and npm lock files

---

job-dsls/jobs/ProdTag_pipeline.groovy

(cherry picked from commit a66316fbac144ec8d981380559e9007ff3e448df)

fixed test result URL in prod tag pipeline

---

job-dsls/jobs/ProdTag_pipeline.groovy

(cherry picked from commit 052447c34dcaaddc64cf7a4eb850d9faa1703015)

fixed email addresses for prod tags

---

job-dsls/jobs/CommunityRelease_pipeline.groovy

the additional test for community releases have to eb configured otherwise then in daily builds.
This was tested and it works now.

changed settings.xml and download URL for community additional tests

---

job-dsls/jobs/sonarcloud_daily.groovy

Added missing Maven settings.xml configuration which includes properties specifying NPM/Yarn registry.

Fix missing settings.xml config for sonar jobs

---

job-dsls/jobs/communityRelease_pipeline.groovy
job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/prodTag_pipeline.groovy

IMPORTANT: Please merge this **after** we released the `7.29.0.Final`
This PR is a personal nitpicking. 
With this PR Jenkins folders and jobs looks more consitent.

defined all folder and job names in lower case

---

jenkins-slaves/ansible/roles/kie/tasks/main.yml

Removing the cache repositories. Temporarily fix.

BXMSPROD-535: updating git repository caches

---

jenkins-slaves/ansible/roles/kie/tasks/main.yml
jenkins-slaves/ansible/roles/rhba/tasks/main.yml
job-dsls/jobs/execute_pig.groovy

BXMSPROD-512
depends on https://github.com/kiegroup/kie-jenkins-scripts/pull/619
* execute_pig label set and folder path errors fixed. 
* rhba/tasks/main.yml repo folder error fixed.

BXMSPROD-512 PiG tool installation. Paths errors fixed.

---

job-dsls/jobs/communityRelease_pipeline.groovy

Once the pipeline is executed twice (or more times) a full build (local deploy and upload artifacts to Nexus) is selectable.

build when executing again pipeline is selectable

---

job-dsls/jobs/prodTag_pipeline.groovy

when trying to push from an arbitrary node something to gerrit a 
git config --global is required

requested global git configuration

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

wildfly profile was removed in optaplanner PRs and the the the deploy job of the repository

removed wildfly profile for optaplanner

---

job-dsls/jobs/pr_jobs.groovy

selects 24 gig nodes for droolsjbpm-integration PRs and also creates a gclog file and stores it

enabled 24gig nodes for droolsjbpm-integration

---

job-dsls/jobs/drools_website_automatic_publishing.groovy
job-dsls/jobs/jbpm_website_automatic_publishing.groovy
job-dsls/jobs/optaplanner_website_automatic_publishing.groovy

DSL jobs that create a docker container for running the automatic publishing process of web pages (drools, jbpm and optaplanner).
These jobs are already existing as Jenkins jobs - but didn't exist as DSL groovy scripts.

New script webs

---

job-dsls/jobs/communityRelease_pipeline.groovy

This change allows to upload binaries to filemgmt also when the pipeline is re-started again only cloning the existing release branches without re-building them again.
The local directory (where binaries are deployed to) and some directories only available in a /target (after a build) are compressed and copied outside the workspace when the pipeline does a build and made available for future pipeline execution without build.

enabled the tar creation of the artifacts to upload

---

job-dsls/jobs/drools_website_automatic_publishing.groovy
job-dsls/jobs/jbpm_website_automatic_publishing.groovy
job-dsls/jobs/optaplanner_website_automatic_publishing.groovy

the folder "websites" is created now in the seed-job directory KIE

fixed path for not creating another KIE folder in KIE

---

job-dsls/jobs/DailyBuild_pipeline.groovy
job-dsls/jobs/DailyBuild_prod_pipeline.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

disabled all automatic jobs (daily builds and PRs and FBDs). In future we should also remove the KIE/7.26.x directory on Jenkins

disabled dailyBuilds and PRs for 7.26.x

---

job-dsls/jobs/communityRelease_pipeline.groovy

- the created binaries by a build will be archieved and are available for new jobs without building again
- the variable myVar was changed by  branchExists as this variable name explains what is it about
- a new hidden variable binariesNR was introduced. This is needed if a user re-triggers a communityRelease_pipeline job WITHOUT wanting to build again but pushing binaries to filemgmt.jboss.org
This was tested on Jenkins (on my custom) linked to my local git hub:
- start pipeline from scratch
- abort pipeline
- restart pipeline with a new build (in case sanity checks had changed something)
- restart pipeline without a new build (in case the sanity checks didn't find any thing)
All cases are covered and the pipeline - it can be aborted without loosing the created binaries.

archived artifacts for future jobs

---

job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy

Mails are only sent to bsig list if build status was UNSTABLE or FAILURE.
When build was successful only a brief mail will send to @mareknovotny @mbiarnes

mails are only sent when build fails or is unstable

---

job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy

(cherry picked from commit 302779352d3b8779e541cdda34affd67dad29c5c)

small fixes and new mail address

---

job-dsls/jobs/communityRelease_pipeline.groovy
job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy

only last mail after sanity checks - when the release was closed and done will be send to bsig list

changed mail recipients

---

job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy

(cherry picked from commit 03307ee40bad57d442a076a9bb1ba1e1e1d12683)
backportet "filter options" from master

change wording in bodies of mail for better gmail filtering

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy

Regex checked via https://regex101.com/

Make trigger phrases for downstream builds more benevolent

---

jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/rhba/tasks/main.yml

BXMSPROD-583
pom-manipulation-ext to pom-manipulation-cli
version upgraded to 3.8.1

BXMSPROD-583 pom-manipulation-ext to pom-manipulation-cli

---

jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/rhba/tasks/main.yml

BXMSPROD-637 pig compilation replaced by pig downloading

---

jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/rhba/tasks/main.yml

BXMSPROD-637 validate_certs flag added to 'Dowload PiG extension' ansible step

---

job-dsls/jobs/communityRelease_pipeline.groovy

- added comments for each step
- added a new stage where a directory (${kieVersion}"_uploadBinaries) is created where the binaries for uploading to filemgmt.jboss.org are stored - later this directory is compressed and archieved)
- a flat file with the content and size of the new dir is created and stored into it - so it is available in the *.tar.gz too
- a new hidden parameter deployPath is created
- due to the big sized file (*.tar.gz, +/- 2G) that is archived the log rotator stores only 3 builds.

created dir for binaries to upload to filemgmt

---

jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/rhba/tasks/main.yml

BXMSPROD-638 PME removed from maven extensions

---

job-dsls/jobs/downstream_pr_jobs.groovy

only for kie-wb-common FDB:
raise the JVM to 7g and disable the multithreading

added different maven command and memory for kie-wb-common FDB

---

job-dsls/jobs/prodTag_pipeline.groovy

@mareknovotny minor fix - this is not important to merge ASAP

job description promp user to use right format

---

job-dsls/jobs/kogito.groovy

- Remove kogito-bom repository
- Add kogito-apps repository

KOGITO-1228 - Kogito release updates

---

jenkins-slaves/ansible/kie-rhel7.yml

Reverts kiegroup/kie-jenkins-scripts#680

Revert "BXMSPROD-583 pom-manipulation-ext to pom-manipulation-cli"

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

@mbiarnes is there any sensible way of testing there changes before we merge it?

Checkout github repository into a separate directory

---

job-dsls/jobs/dailyBuild_pipeline.groovy

Ensemble together with:
- https://github.com/kiegroup/kie-wb-common/pull/3217

KOGITO-1107: Ensure prod daily build pass kie-wb-common selenium test

---

job-dsls/jobs/downstream_pr_jobs.groovy

This reverts commit 6bf3d23b7de66b1e9b014022d9e46610da03b8c8.

Revert "KOGITO-1458: Ensure selenium tests of kie-wb-common run in FDB"

---

job-dsls/jobs/communityRelease_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

parallel additional test execution had to be changed because something in Jenkins/pipelines changed.
Now the pipeline compiles again.

Additional tests community release

---

job-dsls/jobs/kie_jenkinsScripts_PR.groovy

@mareknovotny this PR should changes the kie_jenkinsScripts_PR.groovy  to work with the correct emails sendings. When this works - this changes will be transferred to all other PRs

added POST-BUILD scripts: email and shell scripts

---

job-dsls/jobs/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/pr_jobs.groovy

forced the script building in $WORKSPACE - so script is there and should be found.
This was tested and worked in https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/mbiarnes/job/pullrequest/job/lienzo-tests-pullrequests/ . I hope the same will happen "life" . 
- otherwise we have to roll back this PR again.
(I don't now how to test this in a more realistic environment)

Ext mail pull request

---

job-dsls/jobs/srcclr_scan_job.groovy
job-dsls/jobs/srcclr_scan_pipeline.groovy

Last finishing additions to the job.

BXMSPROD-533-FINISHING

---

jenkins-slaves/ansible/data/service/smee.service
jenkins-slaves/ansible/data/service/smee.service.sh.j2
jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/cert-ssh/tasks/main.yml
jenkins-slaves/ansible/roles/smee/tasks/main.yml
jenkins-slaves/ansible/smee-client.yml
jenkins-slaves/packer-smee-client.json

https://issues.jboss.org/browse/BXMSPROD-131

BXMSPROD-131 smee service

---

jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/kogito/tasks/main.yml

https://issues.redhat.com/browse/BXMSPROD-746
related to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1282

BXMSPROD-746 node version upgraded to 12.16.2

---

job-dsls/jobs/srcclr_scan_job.groovy
job-dsls/jobs/srcclr_scan_pipeline.groovy

After testing it in Jenkins, we found out that the label and node names were not correct. Please, review and merge.

BXMSPROD-533 Corrected node and label names

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/pr_jobs.groovy
job-dsls/jobs/seed_job.groovy

Assuming the next step we do is to change the procedure of PRs and CDB (like we have done so far for the FDB) we should disable the PRs and CDBs as well as remove them from the seed-job so they are not constructed again and overwrite  the recent ones.

Pull requests

---

job-dsls/jobs/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/pr_jobs.groovy
job-dsls/jobs/springboot_pr_job.groovy

https://issues.jboss.org/browse/BXMSPROD-779

BXMSPROD-779 webhook configuration

---

job-dsls/jobs/prod_seed_cloud_jobs.groovy

See: https://issues.redhat.com/browse/KIECLOUD-391
Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>

[KIECLOUD-391] - Configure nightly builds for PIM images on Jenkins

---

jenkins-slaves/ansible/data/config/bashrc
jenkins-slaves/ansible/data/config/podman.conf
jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/common/tasks/main.yml
jenkins-slaves/ansible/roles/kogito/tasks/main.yml

Closses [KOGITO-2383] and [KOGITO-2384]
see: https://issues.redhat.com/browse/KOGITO-2383 && \
https://issues.redhat.com/browse/KOGITO-2384
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

 Changed roles to accomodate the changes for the kogito-cloud pipelines

---

job-dsls/jobs/errai_pr.groovy
job-dsls/jobs/seed_job.groovy

new pull request job for errai PR - works with webhooks but not with Jenkinsfile and shared-libraries
as errai doesn't have FDBs or CDBs or other jobs.
When merged we have to change the seed job!

added new DSL groovy script for errai PRs

---

job-dsls/jobs/deploy_jobs.groovy

this deploy job still failed due known parallel build https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/deployedRep/job/optaweb-employee-rostering/2579/consoleText

deploy jobs needed turn off parallel builds too

---

jenkins-slaves/ansible/data/config/bashrc
jenkins-slaves/ansible/kie-rhel7.yml

See: https://issues.redhat.com/browse/KOGITO-2565
See: https://issues.redhat.com/browse/KOGITO-2591

Update dependency to comply with kogito-cloud-operator

---

job-dsls/jobs/new_compile_downstream_build.groovy
job-dsls/jobs/new_downstream_pr_jobs.groovy
job-dsls/jobs/new_downstream_production.groovy
job-dsls/jobs/new_pr_jobs.groovy
job-dsls/jobs/new_upstream.groovy

`archiveArtifacts` removed because they are already defined here https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/Jenkinsfile#L102 and her https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/Jenkinsfile#L105
related with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1383

remove additional artifacts

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

https://issues.redhat.com/browse/KOGITO-2682

Kogito 2682 - Add missing packages for native build tests

---

job-dsls/jobs/new_pr_jobs.groovy

added war to archive for appformer PR

added dashbuilder-runtime.war for artifacts to archive

---

job-dsls/jobs/new_compile_downstream_build.groovy
job-dsls/jobs/new_downstream_pr_jobs.groovy

A FDB for droolsjbpm-tolls was requested - we simply hadn't one job for this.
Now it will be generated. As @jomarko told, this rep is rarely touched.
But to have it right now doesn't hurt. I the worst case this job never is started.

since a FDB for droolsjbpm-tools was requested it was added

---

job-dsls/jobs/prodTag_pipeline.groovy

(cherry picked from commit 8bdd904dc134b8c43353e51d2941ee715c95ba06)

removed slash that breaks link

---

job-dsls/jobs/dailyBuild_pipeline.groovy

(cherry picked from commit e4badaff41d98ee0d6297e87a5001e492b725830)

changed http to https and modified port of LOCAL_NEXUS_IP

---

job-dsls/jobs/deploy_jobs.groovy

https://issues.redhat.com/browse/BXMSPROD-888

fixed wrong branch for deployment of Optaplanner snapshots

---

job-dsls/jobs/dailyBuild_pipeline.groovy

@mbiarnes Here's the fix. I also added a removal of sources.tar.gz as it was already done in `kieWbTestsMatrix` job.

BXMSPROD-923 - Fix daily builds by replacing rmdir with rm -rf

---

jenkins-slaves/ansible/kie-rhel7.yml

https://issues.redhat.com/browse/KOGITO-2989

[KOGITO-2989] - Upgrade graalvm version on kogito nodes

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

update to 7.44.0

---

job-dsls/jobs/communityRelease_pipeline.groovy
job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/downstream_production.groovy
job-dsls/jobs/drools_website_automatic_publishing.groovy
job-dsls/jobs/errai_pr.groovy
job-dsls/jobs/execute_pig.groovy
job-dsls/jobs/github_api_limit.groovy
job-dsls/jobs/jbpm_website_automatic_publishing.groovy
job-dsls/jobs/kie_build_helper_jenkins_plugin_pr_job.groovy
job-dsls/jobs/optaplanner_website_automatic_publishing.groovy
job-dsls/jobs/pr_jobs.groovy
job-dsls/jobs/seed_job.groovy
job-dsls/jobs/upstream.groovy

This reverts commit c0bd43be86d3bec8a5c367ee8e948be76392bc09.
etc. 
<pre>
</pre>
This PR reverts the PR #816 that was accidentally merged in master instead of 7.44.x branch. The PR couldn't b reverted automatically because one file changed.

Revert "Fix 7.44.x (#816)"

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/kie_docs_pr.groovy

last fixes for scripts to run on 7.44.x branch

---

job-dsls/jobs/prodTag_pipeline.groovy

fixed the URL to tests

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

added master-kogito branch to kie-docs PRs

---

job-dsls/jobs/pr_jobs.groovy

etc. 
<pre>
</pre>
@rsynek @Ginxo optaplanner PR has not any more "master" as white listed branch

excluded whitelisted master branch form optaplanner PRs

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

Increased the maximum number of open files system limit for jenkins user in the images.

images: increase max number of open files

---

job-dsls/jobs/pr_jobs.groovy

https://issues.redhat.com/browse/JBPM-9357
* https://github.com/kiegroup/jbpm-work-items/pull/158
<pre>
</pre>
please delete source branch after merging it

update pr jobs to increase jbpm-work-items timeout

---

job-dsls/jobs/deploy_jobs_7_x.groovy
job-dsls/jobs/seed_job.groovy

BXMSPROD-1036: added deploy jobs for opta* 7.x

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

updated constants to sync with master branch version

---

job-dsls/jobs/deploy_jobs.groovy

[BXMSPROD-1056](https://issues.redhat.com/browse/BXMSPROD-1056)
etc. 
<pre>
</pre>

BXMSPROD-1056: removed upstream builds for deploy jobs

---

job-dsls/jobs/reduced_drools_release.groovy
job-dsls/jobs/seed_job.groovy

[BXMSPROD-1038](https://issues.redhat.com/browse/BXMSPROD-1038?filter=-1)
etc. 
<pre>
</pre>

BXMSPROD-1038: Create short release pipeline just for drools

---

job-dsls/jobs/errai_deploy.groovy
job-dsls/jobs/seed_job.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/ErraiDeployJob.groovy

[BXMSPROD-1057](https://issues.redhat.com/browse/BXMSPROD-1057)
etc. 
<pre>
</pre>

BXMSPROD-1057: new DSL groovy script for deploy of errai

---

job-dsls/build.gradle
job-dsls/jobs/kieAll_meta_pipeline.groovy
job-dsls/jobs/kie_docker_ui_webapp.groovy
job-dsls/jobs/kie_tools_seed_job.groovy
job-dsls/jobs/send_UMB_trigger_after_version_upgrade.groovy

[BXMSPROD-1012](https://issues.redhat.com/browse/BXMSPROD-1012)
etc. 
<pre>
</pre>

New dsl groovy scripts

---

job-dsls/jobs/deploy_development_version.groovy
job-dsls/jobs/kieAll_meta_pipeline.groovy
job-dsls/jobs/kie_tools_seed_job.groovy

fixed leftover minor bugs

---

job-dsls/jobs/deploy_jobs.groovy

prevented branch name to be printed twice in zulip stream

---

job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/deploy_development_version.groovy

fixed wrong order - sshagent has to be in step section

---

jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/common/tasks/main.yml
jenkins-slaves/ansible/roles/kogito/tasks/main.yml

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1062
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1508
* https://github.com/kiegroup/kie-jenkins-scripts/pull/843
etc. 
<pre>
</pre>

BXMSPROD-1062 buil chain action installation

---

job-dsls/jobs/prod_projects_downstream_production.groovy
job-dsls/jobs/seed_job.groovy

[BXMSPROD-1061](https://issues.redhat.com/browse/BXMSPROD-1061)
etc. 
<pre>
</pre>

BXMSPROD-1061: DSL groovy script for rhba production full downstream build

---

job-dsls/jobs/kogito_docs_upload.groovy

added email ext step

---

job-dsls/jobs/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kieAll_meta_pipeline.groovy
job-dsls/jobs/seed_job.groovy

BXMSPROD-616: Added daily build job for JDK 11

---

job-dsls/jobs/reduced_drools_release.groovy

[BXMSPROD-1083](https://issues.redhat.com/browse/BXMSPROD-1083)
etc. 
<pre>
</pre>

BXMSPROD-1083: added step for pushing tag

---

job-dsls/jobs/communityRelease_pipeline.groovy
job-dsls/jobs/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/deploy_development_version.groovy
job-dsls/jobs/prodTag_pipeline.groovy
job-dsls/jobs/reduced_drools_release.groovy

[BXMSPROD-1084](https://issues.redhat.com/browse/BXMSPROD-1084)
etc. 
<pre>
</pre>

BXMSPROD-1084: changed execution command

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

bumped up prefix for KIE daily builds

---

job-dsls/build.gradle

**JIRA**:  [BXMSPROD-1092](https://issues.redhat.com/browse/BXMSPROD-1092)
<pre>
</pre>

BXMSPROD-1092: added new repository

---

job-dsls/build.gradle

changed jenkins-ci.org from release to public

---

job-dsls/jobs/automatic_web_publishing.groovy

[BXMSPROD-1091](https://issues.redhat.com/browse/BXMSPROD-1091)
etc. 
<pre>
</pre>

BXMSPROD-1091: add mail sendings to web-publishing jobs

---

jenkins-slaves/ansible/kie-rhel7.yml

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1062
<pre>
</pre>

BXMSPROD-1062 buil chain action upgrade to 2.0.0

---

jenkins-slaves/ansible/data/config/docker/daemon.json
jenkins-slaves/ansible/data/config/docker/docker

Lowered Docker network MTU configuration to match the Jenkins agent environment.
**JIRA**: [BXMSPROD-1089](https://issues.redhat.com/browse/BXMSPROD-1089)
<pre>
</pre>

BXMSPROD-1089: lower Docker network mtu to comply with PSI

---

job-dsls/jobs/slave_image_build.groovy

Updates the image creation Jenkins job DSL definition to the changes introduced in \[1].
<pre>
</pre>
\[1] https://github.com/kiegroup/kie-jenkins-scripts/pull/861

JobDSL: update slave-image-build job to the changes in image tooling

---

jenkins-slaves/ansible/kie-rhel.yml
jenkins-slaves/ansible/roles/common/tasks/main.yml

**JIRA**: _https://issues.redhat.com/browse/BXMSPROD-851_

[BXMSPROD-851] - Upgrade jdk for 8 and 11 on openstack nodes to the latest versions

---

job-dsls/jobs/jenkins_shared_libs.groovy

https://issues.redhat.com/browse/BXMSPROD-1132
<pre>
</pre>

[BXMSPROD-1132] Setup shared libs pr job

---

job-dsls/jobs/seed_job.groovy

https://issues.redhat.com/browse/BXMSPROD-1132

[BXMSPROD-1132] Update seed_job.groovy

---

jenkins-slaves/ansible/roles/kogito/tasks/main.yml

https://issues.redhat.com/browse/BXMSPROD-1128
* https://gitlab.cee.redhat.com/middleware/build-configurations/-/merge_requests/226
* https://github.com/kiegroup/kogito-tooling/pull/342
<pre>
</pre>

[BXMSPROD-1128] kogito-tooling libraries

---

job-dsls/jobs/downstream_pr_jobs.groovy

increased timeout for fdb

---

job-dsls/jobs/springboot_pr_job.groovy

added pr extension to springboot pullrequest job

---

job-dsls/jobs/kieAll_meta_pipeline.groovy

added daily builds for new 7.48.x branch

---

job-dsls/jobs/kieAll_meta_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

- enabled daily build of 7.48.x using JAVA 11
- upgraded Constant value 7.49.0 (since master has 7.49.0-SNAPSHOT)
<pre>
</pre>

Meta pipeline

---

job-dsls/jobs/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/seed_job.groovy

Docker 7.48.x

---

job-dsls/jobs/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/dailyBuild_pipeline.groovy

Docker master

---

job-dsls/jobs/deploy_jobs.groovy

increased timeout value to prevent aborting build

---

jenkins-slaves/ansible/kie-rhel.yml
jenkins-slaves/ansible/roles/kogito/tasks/main.yml

https://issues.redhat.com/browse/BXMSPROD-1128
<pre>
</pre>

BXMSPROD-1128 npm-cli-login library

---

jenkins-slaves/ansible/data/config/verdaccio/config.yaml
jenkins-slaves/ansible/data/config/verdaccio/htpasswd
jenkins-slaves/ansible/data/config/verdaccio/htpasswd.j2
jenkins-slaves/ansible/data/service/verdaccio.service
jenkins-slaves/ansible/data/service/verdaccio.service.sh.j2
jenkins-slaves/ansible/roles/node/tasks/main.yml
jenkins-slaves/ansible/roles/smee/tasks/main.yml
jenkins-slaves/ansible/roles/verdaccio/tasks/main.yml
jenkins-slaves/ansible/verdaccio-service.yml
jenkins-slaves/packer-verdaccio-client.json

https://issues.redhat.com/browse/BXMSPROD-1147
<pre>
</pre>

BXMSPROD-1147 verdaccio service creation

---

job-dsls/jobs/communityRelease_pipeline.groovy

removed wildfly version in mails

---

job-dsls/jobs/seed_job.groovy

https://github.com/kiegroup/kie-jenkins-scripts/pull/903
<pre>
</pre>

removed JDK11 daily build pipeline

---

job-dsls/jobs/communityRelease_pipeline.groovy

<pre>
</pre>
The previous curl command only worked if you wrote it directly in a pipeline - if you create a pipeline fvia a DSL groovy file it should be like now.

fixed curl command

---

jenkins-slaves/ansible/data/config/bashrc
jenkins-slaves/ansible/kie-rhel.yml
jenkins-slaves/ansible/roles/common/tasks/main.yml

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
**JIRA**:  https://issues.redhat.com/browse/KOGITO-4063 
[Tested with test-image](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kaitou786/job/new-image-test/11/console)
etc. 
<pre>
</pre>

[KOGITO-4063] - Update nightly and PR check image with operator-sdk 1.2

---

job-dsls/jobs/reduced_drools_release.groovy

Fixing the missing $ for javadk variable
<pre>
</pre>

fixed referencing the value from variable

---

jenkins-slaves/ansible/kie-rhel.yml
jenkins-slaves/ansible/roles/gh-api/tasks/main.yml

https://issues.redhat.com/browse/BXMSPROD-1175
<pre>
</pre>

BXMSPROD-1175 Install gh-api

---

jenkins-slaves/ansible/kie-rhel.yml

[ISSUE 126] build-chain-tool upgraded to 2.2.14

---

jenkins-slaves/ansible/kie-rhel.yml

* https://github.com/kiegroup/github-action-build-chain/pull/128
<pre>
</pre>

[ISSUE 126] build chain upgraded to ^2.2.15

---

job-dsls/jobs/communityRelease_pipeline.groovy

[BXMSPROD-1124](https://issues.redhat.com/browse/BXMSPROD-1124)
* https://github.com/kiegroup/kie-jenkins-scripts/pull/877 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1556
<pre>
</pre>

Bxmsprod 1124

---

job-dsls/jobs/deploy_jobs.groovy

This reverts commit 33e5faf6936609d90598a344f8d86685fe5845eb.
<pre>
</pre>

Revert "Use JDK 11 for optawebs and optaplanner-quickstarts (#867)"

---

jenkins-slaves/ansible/data/config/bashrc

https://issues.redhat.com/browse/BXMSPROD-1183
<pre>
</pre>

BXMSPROD-1183 GRAALVM_HOME moved at the end of the PATH

---

job-dsls/jobs/dailyBuild_pipeline.groovy

additional tests are not executed any more on master

---

job-dsls/jobs/communityRelease_pipeline.groovy

fixed typo

---

job-dsls/jobs/new_branches_seed_job.groovy
job-dsls/jobs/osbs_seed_job.groovy

This new seed job is for the new branches that will be created based on master branch. In branches NOT master there are less jobs to create. Until now the seed-job from master was copied to the new branch and the superfluous jobs were removed.
<pre>
</pre>

added new seed job for all new branches

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

Add passwordless sudo capability for Jenkins user

---

job-dsls/jobs/dailyBuild_pipeline.groovy

The version has to be shortened to avoid `Argument list too long` failures in daily builds and nightlies
https://github.com/kiegroup/kie-jenkins-scripts/pull/928
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/140
<pre>
</pre>

shortened version

---

job-dsls/jobs/dailyBuild_jdk11_pipeline.groovy

shortening version to avoid "Argument list too long" at https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/daily-build-jdk11/job/daily-build-jdk11-pipeline-master
similar to https://github.com/kiegroup/kie-jenkins-scripts/pull/928
<pre>
</pre>

Shortening versions to yyMMDD-hh

---

job-dsls/jobs/replace_shared_libraries.groovy
job-dsls/jobs/rhbaProdReplaceVersion.groovy
job-dsls/jobs/rhba_prod_branch.groovy
job-dsls/jobs/shared_libraries_new_branch.groovy
job-dsls/jobs/slave_image_build_PR_test.groovy

added new missing DSL groovy scripts in Jenkins/PROD
<pre>
</pre>

New dsl for migration

---

job-dsls/README.MD
job-dsls/jobs/prod_offline_repo_builder.groovy
job-dsls/jobs/prod_rhba_properties_generator.groovy
job-dsls/jobs/prod_rhba_staging.groovy
job-dsls/jobs/seed_job.groovy
job-dsls/src/main/resources/job-scripts/prod_offline_repo_builder.sh
job-dsls/src/main/resources/job-scripts/prod_rhba_properties_generator.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_staging.jenkinsfile

DSLs for the following jobs in the PROD folder:
- rhba-properties-generator
- offline-repo-builder
- rhba-staging

PROD jobs and pipelines DSLs

---

job-dsls/jobs/kie_seed_job.groovy
job-dsls/jobs/kie_tools_seed_job.groovy
job-dsls/jobs/prod_seed_job.groovy

A seed job

---

job-dsls/jobs/prod_kogito_properties_generator.groovy
job-dsls/jobs/prod_seed_job.groovy

added DSL groovy script for kogito-properties-generator

---

job-dsls/jobs/communityRelease_pipeline.groovy

Fixes definitely the malformed URLs when sending the mail for Sanity Checks
<pre>
</pre>

fixed mail sending, URLs point to right target

---

job-dsls/jobs/prodTag_pipeline.groovy

added tag name in first mails sent

---

job-dsls/jobs/pr_jobs.groovy

increased timeout value for drools pullrequest

---

jenkins-slaves/ansible/data/config/pulp/pulp-rhel7.repo
jenkins-slaves/ansible/data/config/pulp/pulp-rhel8.repo
jenkins-slaves/ansible/roles/common/tasks/main.yml

The pulp repository location has changed, it needs to be reflected otherwise yum/dnf package installation will fail.
<pre>
</pre>

images: use new pulp repository location

---

job-dsls/jobs/tools/tools_provisioning_cekit.groovy
job-dsls/jobs/tools/tools_provisioning_delete.groovy
job-dsls/jobs/tools/tools_provisioning_docker_reg.groovy
job-dsls/jobs/tools/tools_provisioning_smee_client.groovy
job-dsls/jobs/tools/tools_provisioning_verdaccio.groovy

- secret file had to be added since Global Passwords are not not supported in Jenkins config migration 
- the name of the machines changed to prevent confusions when having tow Jenkinses 
<pre>
</pre>

added secret text and changed machine names

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

synced with master version

---

job-dsls/jobs/kie/master/compile_downstream_build.groovy
job-dsls/jobs/kie/master/downstream_pr_jobs.groovy
job-dsls/jobs/kie/master/downstream_production.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy
job-dsls/jobs/kie/master/upstream.groovy

Move to Jenkinsfile.buildchain
https://github.com/kiegroup/kie-jenkins-scripts/pull/932
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1587
<pre>
</pre>

use of Jenkinsfile.buildchain for all PRs

---

job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy

fixed name of groovy jobs

---

job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy

- replaced UMB trigger by CRON trigger
- replaced 7.48.x daily builds by 7.52.x + added JDK 11 daily build for 7.52.x
- replaced obsolete trigger definition in pipeline job by `gitHubPushTrigger()`
- added some additional label definitions
<pre>
</pre>

replaced deprecated trigger configuration

---

job-dsls/jobs/kie/master/compile_downstream_build.groovy
job-dsls/jobs/kie/master/downstream_pr_jobs.groovy
job-dsls/jobs/kie/master/downstream_production.groovy
job-dsls/jobs/kie/master/jenkins_shared_libs.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy
job-dsls/jobs/kie/master/upstream.groovy

replaced deprecated pipeline trigger configuration

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy

enabled Xvnc in community pipeline

---

job-dsls/jobs/seed_jobs/kie_master_branch_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_docs_seed_job.groovy
job-dsls/jobs/seed_jobs/migration_seed_job.groovy
job-dsls/jobs/seed_jobs/osbs_seed_job.groovy
job-dsls/jobs/seed_jobs/prod_seed_job.groovy
job-dsls/jobs/seed_jobs/tools_seed_job.groovy

fixed seed jobs

---

jenkins-slaves/ansible/kie-rhel.yml

https://issues.redhat.com/browse/BXMSPROD-1252
<pre>
</pre>

BXMSPROD-1252 buildchain_version upgraded to 2.2.21

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy

moved Xvnc into configFileProvider

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

bumped up to next kie version prefix

---

job-dsls/jobs/kie/master/automatic_web_publishing.groovy

This PR needs first have merged #960 since a new Jenkins and DSL and github plugin version is required, otherwise the build fails.
Suggestion: merge this PR after #960 - so after migration to `eng-jenkins`
<pre>
</pre>

updated triggers to new DSL conf.

---

job-dsls/jobs/kie/master/pr_jobs_7_x.groovy

the opta* pullrequests will appear as `opta*_7.x.pr` - not any more as misleading  `opta*-master.pr`
<pre>
</pre>

separated pr jobs for master and 7.x

---

job-dsls/build.gradle
job-dsls/gradle.properties
job-dsls/jobs/kie/master/prodTag_pipeline.groovy
job-dsls/jobs/tools/tools_provisioning_verdaccio.groovy

This should be merged AFTER Jenkins (`eng-jenkins`) was upgraded to 2.277.2 
<pre>
</pre>

all needed updates for upgrade to Jenkins 2.277.2

---

job-dsls/build.gradle
job-dsls/gradle.properties
job-dsls/jobs/kie/master/prodTag_pipeline.groovy
job-dsls/jobs/tools/tools_provisioning_verdaccio.groovy

This should be merged AFTER Jenkins (`eng-jenkins`) was upgraded to 2.277.2 
<pre>
</pre>

Upgrade jenkins

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy
job-dsls/jobs/kie/master/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/master/dailyBuild_pipeline.groovy
job-dsls/jobs/kie/master/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/kie/master/prodTag_pipeline.groovy

added timestamp for better seeing a jobs process

---

jenkins-slaves/ansible/kie-rhel.yml
jenkins-slaves/ansible/roles/common/tasks/main.yml

Ant installation needed for creation of jbpm-installers during the community pipeline
<pre>
</pre>

added Ant neded for creation of jbpm-installers

---

job-dsls/jobs/prod/prod_rhba_staging.groovy
job-dsls/src/main/resources/job-scripts/prod_rhba_staging.jenkinsfile

Fix RHBA PROD staging job adding latest PNC API changes

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

fixed typo in main.yaml

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

added missing space

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

fixed typos

---

job-dsls/jobs/prod/prod_kogito_properties_generator.groovy
job-dsls/jobs/prod/prod_rhba_properties_generator.groovy

[NIGHTLY] prod_*_properties_generator missing agent fixed

---

job-dsls/jobs/kie/master/compile_downstream_build.groovy
job-dsls/jobs/kie/master/deploy_jobs.groovy
job-dsls/jobs/kie/master/deploy_jobs_7_x.groovy
job-dsls/jobs/kie/master/downstream_pr_jobs.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy
job-dsls/jobs/kie/master/pr_jobs_7_x.groovy
job-dsls/jobs/kie/master/springboot_pr_job.groovy

replaced checkstyle files

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

absolute NOT urgent
<pre>
</pre>

nitpicking: replaced double by single quotes

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

changed daily builds kie prefix to 7.55.0

---

job-dsls/jobs/tools/tools_provisioning_smee_client.groovy
job-dsls/jobs/tools/tools_provisioning_verdaccio.groovy

replaced parameter values for smee clients

---

job-dsls/jobs/kie/master/errai_pr.groovy

make available retesting the errai PR

---

job-dsls/jobs/kie/master/errai_pr.groovy
job-dsls/jobs/kie/master/jenkins_shared_libs.groovy
job-dsls/jobs/kie/master/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy
job-dsls/jobs/kie/master/pr_jobs_7_x.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrDroolsjbpmToolsJob.groovy

Fix the trigger string to more accepting, for example "jenkins retest please" as seen in: 
https://github.com/kiegroup/kogito-examples/pull/685

Fix trigger string to accept more loosely based requests.

---

job-dsls/jobs/kie/master/kie_jenkinsScripts_PR.groovy

increased timeout values

---

job-dsls/jobs/kie/master/kie_jenkinsScripts_PR.groovy

removed timeout

---

jenkins-slaves/ansible/data/config/bashrc

Added ant directory to PATH in the same way as Maven is.
<pre>
</pre>

images: add ant to PATH

---

job-dsls/jobs/kie/master/compile_downstream_build.groovy
job-dsls/jobs/kie/master/downstream_pr_jobs.groovy
job-dsls/jobs/kie/master/downstream_production.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy
job-dsls/jobs/kie/master/prodProjects_downstream_production.groovy
job-dsls/jobs/kie/master/upstream.groovy

the cancelOnUpdate is now enabled on all PR jobs on the `eng-jenkins`
<pre>
</pre>

[7.52.x] added cancelBuildOnUpdate

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

upgraded master version prefix

---

job-dsls/jobs/prod/prod_rhba_replace_version.groovy

The branching part is carried out by the prod_rhba_prod_branch. This pipeline adjusts versions for KIE and RHBA.
**JIRA**: _BXMSPROD-1102_ 
<pre>
</pre>

[BXMSPROD-1102] - Change the rhba version along with kie version for specific checked out branch

---

job-dsls/jobs/prod/prod_rhba_replace_version.groovy

**JIRA**: _BXMSPROD-1102_ 
<pre>
</pre>

[BXMSPROD-1102] - Adjusted the default RHBA version

---

job-dsls/jobs/prod/prod_rhba_properties_generator.groovy

Add a symlink to the latest nightly properties so it can be referenced without specifying a date

Symlink latest nightly properties

---

jenkins-slaves/ansible/kie-rhel.yml

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1361
<pre>
</pre>

BXMSPROD-1361 build-chain upgraded to 2.3.4

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy

Seen directly on Jenkins that this works as expected when using `--global` and the right email address for kie-ci.
This can and will overwrite if a user.name and user.email if this already exist on a machine.
<pre>
</pre>

add right usr metadata for github

---

job-dsls/jobs/prod/prod_rhba_replace_version.groovy

Fixed script error by changing the equals sign to colon.

Fixed equals sign typo

---

job-dsls/jobs/prod/prod_rhba_replace_version.groovy

Fixed parameter error

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

upgraded constant master prefix to 7.57.0

---

job-dsls/jobs/kie/master/prodTag_pipeline.groovy
job-dsls/jobs/kie/master/reduced_drools_release.groovy

changed order in steps & fixed a typo

---

job-dsls/jobs/kie/master/compile_downstream_build.groovy
job-dsls/jobs/kie/master/downstream_pr_jobs.groovy
job-dsls/jobs/kie/master/downstream_production.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy
job-dsls/jobs/kie/master/pr_jobs_7_x.groovy
job-dsls/jobs/kie/master/upstream.groovy

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1671/files
<pre>
</pre>

buildJDKTool and buildMavenTool

---

jenkins-slaves/ansible/data/config/bashrc
jenkins-slaves/ansible/kie-rhel.yml
jenkins-slaves/ansible/roles/common/tasks/main.yml
job-dsls/jobs/kie/kie-tools/send_UMB_trigger_after_version_upgrade.groovy
job-dsls/jobs/prod/prod_rhba_replace_version.groovy
job-dsls/jobs/prod/prod_shared_libraries_new_branch.groovy
job-dsls/jobs/tools/tools_slave_image_build_PR_test.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

**JIRA**: _BXMSPROD-1339_ 
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1015
<pre>
</pre>

[BXMSPROD-1339] - Changed to maven version 3.8.1

---

job-dsls/jobs/kie/master/prodTag_pipeline.groovy

(cherry picked from commit f7667fd146f306255e5fb0dd6e3c2e177bd2e6c9)
this works - maybe it is not the best solution 
<pre>
</pre>

repeatable step

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Add steps to be compliant with Jenkins pipeline DSL

---

job-dsls/jobs/kie/master/pr_jobs.groovy

removed optaplanner master PRs from Linux - Pull Request

---

job-dsls/jobs/kie/master/pr_jobs.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1252
* https://github.com/jboss-integration/kogito-rhba/pull/23
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1027
<pre>
</pre>

BXMSPROD-1252 kogito-rhba pull request jenkins job

---

job-dsls/jobs/kie/master/pr_jobs.groovy

it fixes https://github.com/kiegroup/kie-jenkins-scripts/pull/1028
<pre>
</pre>

fix ghOrgUnit default value

---

job-dsls/jobs/kie/master/compile_downstream_build.groovy
job-dsls/jobs/kie/master/downstream_pr_jobs.groovy
job-dsls/jobs/kie/master/downstream_production.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy
job-dsls/jobs/kie/master/pr_jobs_7_x.groovy
job-dsls/jobs/kie/master/prodProjects_downstream_production.groovy
job-dsls/jobs/kie/master/upstream.groovy
job-dsls/jobs/prod/prod_replace_shared_libraries.groovy

**JIRA**: https://issues.redhat.com/browse/PLANNER-2467
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1025
* https://github.com/jboss-integration/rhba/pull/42
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1688
<pre>
</pre>

PLANNER-2467 Jenkinsfiles moved to .ci/jenkins

---

job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy

changed CRON for all daily-builds

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

updated suffix 7.58.0 for daily builds

---

jenkins-slaves/ansible/kie-rhel.yml
job-dsls/jobs/tools/tools_slave_image_build.groovy
job-dsls/jobs/tools/tools_slave_image_build_PR_test.groovy

**JIRA**: _BXMSPROD-1190_ 
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1007

[BXMSPROD-1190] - Upgrade PME

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy
job-dsls/jobs/kie/master/dailyBuild_pipeline.groovy

removed duplicated label name and obsolete mvn command

---

job-dsls/jobs/kie/master/downstream_pr_jobs.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy

[BXMSPROD-1387](https://issues.redhat.com/browse/BXMSPROD-1387)
https://github.com/kiegroup/process-migration-service/pull/1
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1694
https://github.com/kiegroup/kie-jenkins-scripts/pull/1036
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)

added PR and FDB for process-migration-service

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy

removed superfluous whitespaces

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1354
* https://github.com/kiegroup/kogito-tooling/pull/557
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1035
<pre>
</pre>

[BXMSPROD-1354] prod_cron_meta_nightly_pipeline kogito-tooling DEPLOYMENT_REPO_URL

---

job-dsls/jobs/kie/master/downstream_pr_jobs.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy

Since process-migrations-services is on the `main` branch we had to add this branch to the ghprb for all PS and FDBs.
<pre>
</pre>

added main branch to ghprb for PRs and FDBs

---

job-dsls/jobs/kie/master/reduced_drools_release.groovy

avoid  permission errors during pushing tags to github

---

job-dsls/jobs/kie/main/srcclr_scan_pipeline.groovy

Added a trigger to run the pipeline each two weeks on 14th and 28th of a month
**JIRA**: _BXMSPROD-806_ 
<pre>
</pre>

[BXMSPROD-806] - Added a trigger to run the pipeline each two weeks

---

job-dsls/jobs/kie/main/pr_jobs.groovy
job-dsls/jobs/kie/main/pr_jobs_7_x.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1425
<pre>
</pre>

BXMSPROD-1425 ghprbTrigger.excludedRegions

---

jenkins-slaves/ansible/roles/rhba/tasks/main.yml

**JIRA**: _BXMSPROD-1419_ 
<pre>
</pre>

[BXMSPROD-1419] - Removed version from the PME jar

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Add a parameter to specify the branch used for the configuration repo

---

jenkins-slaves/ansible/kie-rhel.yml

https://issues.redhat.com/browse/PLANNER-2474
* https://github.com/kiegroup/optaplanner/pull/1440
* https://github.com/kiegroup/optaplanner-quickstarts
* https://github.com/kiegroup/kogito-pipelines/pull/215
<pre>
</pre>

PLANNER-2474 build-chain version upgraded to 2.3.7

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Add parameter for the default branch for the Kogito config repo

---

job-dsls/jobs/kie/kogito/kogito_docs_upload.groovy

closed stages before post actions

---

job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy

removed 7.52.x daily builds

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

disabled nightly for 7.52.x

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

bumped up KIE_PREFIX

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Disable Kogito 1.5.x nightly

---

job-dsls/jobs/kie/main/communityRelease_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_pipeline.groovy

The additional test for a community release or the daily builds fail a lot of times cause time-out issues.
<pre>
</pre>

increased timeout value for additional tests

---

job-dsls/jobs/kie/main/srcclr_scan_job.groovy
job-dsls/jobs/kie/main/srcclr_scan_pipeline.groovy

**JIRA**: _BXMSPROD-806_ 
<pre>
</pre>

BXMSPROD-806 - Invoke srcclr jobs each two weeks

---

job-dsls/jobs/kie/main/communityRelease_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_pipeline.groovy

increased timout again

---

job-dsls/jobs/kie/main/communityRelease_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/pr_jobs.groovy
job-dsls/jobs/kie/main/turtleTests.groovy

replaced kie-linux by kie-rhel7

---

job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/kie/main/prodTag_pipeline.groovy

added new label for pipeline-jobs

---

job-dsls/jobs/prod/prod_rhba_replace_version.groovy

Save changes in all Maven modules.

Save all changed files when updating PROD repository versions

---

job-dsls/jobs/kie/main/communityRelease_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/kie/main/prodTag_pipeline.groovy

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1726
https://github.com/kiegroup/kie-jenkins-scripts/pull/1060
<pre>
</pre>

update version works now with the right settings.xml

---

job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile

Exclude PNC temporary builds for using them with Prod PR check jobs

---

job-dsls/jobs/kie/main/downstream_pr_jobs.groovy

increased timeout for droolsjbpm-build-bootstrap FDB

---

jenkins-slaves/ansible/data/config/verdaccio/config.yaml.j2
jenkins-slaves/ansible/data/config/verdaccio/htpasswd.j2
jenkins-slaves/ansible/data/service/smee.service.sh.j2
jenkins-slaves/ansible/data/service/verdaccio.service.sh.j2
jenkins-slaves/ansible/roles/cert-ssh/tasks/main.yml
jenkins-slaves/ansible/roles/cert-ssh/vars/main.yml
jenkins-slaves/ansible/roles/node/vars/main.yml
jenkins-slaves/ansible/roles/smee/handlers/main.yml
jenkins-slaves/ansible/roles/smee/tasks/main.yml
jenkins-slaves/ansible/roles/smee/vars/main.yml
jenkins-slaves/ansible/roles/verdaccio/handlers/main.yml
jenkins-slaves/ansible/roles/verdaccio/tasks/main.yml
jenkins-slaves/ansible/roles/verdaccio/vars/main.yml
jenkins-slaves/ansible/smee-client.yml
jenkins-slaves/ansible/verdaccio-service.yml
jenkins-slaves/packer-smee-client.json
jenkins-slaves/packer-verdaccio-client.json
job-dsls/jobs/tools/tools_provisioning_smee_client.groovy
job-dsls/jobs/tools/tools_provisioning_verdaccio.groovy

I've noticed several things to improve after RH294 training. Please check. verdaccio and smee related roles are more aligned with ansible-galaxy roles format.

Improve ansible roles

---

job-dsls/jobs/kie/main/reduced_drools_release.groovy

The changes of https://github.com/kiegroup/kie-jenkins-scripts/pull/1060 had to be applied here too since update-versions-all.sh is used
*<pre>
</pre>

changed update version to take the right settings.xml file

---

job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/deploy_jobs_7_x.groovy

maven settings was pointing to wrong settings.xml
<pre>
</pre>

added right settings for deploying to SNAPSHOT

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

https://issues.redhat.com/browse/BXMSPROD-1441
<pre>
</pre>

[BXMSPROD-1441] cron meta nightly PRODUCT_VERSION upgraded to 7.12.0

---

job-dsls/jobs/kie/main/downstream_pr_jobs.groovy

increased value for timeout to prevent the job is timed out

---

job-dsls/jobs/kie/main/downstream_pr_jobs.groovy
job-dsls/jobs/kie/main/pr_jobs.groovy

https://issues.redhat.com/browse/BAPL-1893
* rhttps://github.com/kiegroup/process-migration-service/pull/2
<pre>
</pre>

BAPL-1893 process-migration-service to jdk11

---

job-dsls/jobs/tools/tools_provisioning_smee_client.groovy

Migrate Jenkins to OCP BM

---

job-dsls/jobs/kie/kie-tools/deploy_development_version.groovy

added via configProvider right settings.xml

---

job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy

added line break

---

job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy

changed the paths in seed job

---

job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy

leftover:fixed path in seed-job

---

job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/deploy_jobs_7_x.groovy

- changed the dependant projects following the https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/main/docs/project-dependencies-hierarchy.png
- disabled optaplanner main PR since this is done in kogito
- the opta* - 7.x deploy jobs are also in the same folder as the other for main
<pre>
</pre>

new order jobs following repository-list.txt

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

(kogito: 1.11.x; kogito-tooling: 0.13.0-prerelease)

Add triggering pipelines for 7.12 nightlies

---

job-dsls/jobs/kie/main/i18n_translations.groovy

fixed typos in mail message

---

job-dsls/jobs/kie/main/communityRelease_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/kie/main/prodTag_pipeline.groovy

Added an extra stage for the compilation of `propcess-migration-services` with jdk11.
Has to be merged together with 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1744
<pre>
</pre>

compile process-migration-service with jdk11 in all pipelines

---

job-dsls/jobs/kie/main/deploy_jobs.groovy

(cherry picked from commit 8a9f70a7fab84e6d05685138a5a545f2045d0cba)
<pre>
</pre>

PIM deploy-job build now with jdk11

---

job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/kie/main/prodTag_pipeline.groovy

removed clean-up.sh script from process-migration-service maven command

---

job-dsls/jobs/kie/main/downstream_pr_jobs.groovy

@mareknovotny has to be merged together with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1748
<pre>
</pre>

removed PIM from FDB and CDB

---

job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy
job-dsls/jobs/kie/main/communityRelease_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_prod_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk8_pipeline.groovy
job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/deploy_jobs_7_x.groovy
job-dsls/jobs/kie/main/prodTag_pipeline.groovy
job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

**JIRA**: [BXMSPROD-1468](https://issues.redhat.com/browse/BXMSPROD-1468) 
<pre>
</pre>

BXMSPROD-1468: switch all jobs to JDK 11

---

job-dsls/build.gradle
job-dsls/jobs/prod/prod_multibranch_nightly.groovy

[BXMSPROD-1443](https://issues.redhat.com/browse/BXMSPROD-1443)
<pre>
</pre>

BXMSPROD-1443: DSL groovy script for nightlies

---

job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy

fixed path names

---

job-dsls/jobs/kie/main/i18n_translations.groovy

changed output filename to preserve right path

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Kogito tooling is not needed to be productized so removing trigger for nightly prod job
<pre>
</pre>

Commented out the kogito tooling prod job trigger

---

job-dsls/jobs/prod/prod_multibranch_nightly.groovy

according to comment https://github.com/kiegroup/kie-jenkins-scripts/pull/1102#discussion_r705115276 this job is not needed, but I've created PR just in case we want the job to be updated according to https://github.com/kiegroup/kogito-tooling/pull/624
<pre>
</pre>

kogito-tooling job enabled

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Fix syntax error in prod cron meta nightly pipeline

---

job-dsls/jobs/kie/main/dailyBuild_jdk11_prod_pipeline.groovy

reduced the length of version

---

job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk8_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

**Thank you for submitting this pull request** 
<pre>
</pre>

renewed EAP download URL pointing to 7.4

---

README.md
jenkins-agents/ansible/kie-rhel.yml
jenkins-agents/ansible/roles/common/tasks/main.yml
jenkins-agents/ansible/roles/jdk/tasks/main.yml

jdk17 added to kie-rhel machine

---

job-dsls/jobs/prod/prod_pr_jobs.groovy
job-dsls/jobs/prod/prod_rhba_properties_generator.groovy
job-dsls/src/main/resources/job-scripts/prod_rhba_properties_generator.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_staging.jenkinsfile

**JIRA**:
https://issues.redhat.com/browse/BXMSPROD-1482
* https://github.com/jboss-integration/rhba/pull/51
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1119
* https://github.com/jboss-integration/rhba-installers/pull/95
* https://github.com/kiegroup/kie-wb-distributions/pull/1133
<pre>
</pre>

BXMSPROD-1482 drop RHDM

---

jenkins-agents/ansible/kie-rhel.yml

https://github.com/kiegroup/github-action-build-chain/pull/177
<pre>
</pre>

build-chain upgraded to 2.3.11

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Product nightly for main branches is now 7.13.0
<pre>
</pre>

[prod nightly] 7.13.0

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Comment out Kogito Tooling job triggering

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1783
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1124
<pre>
</pre>

prod_cron_meta_nightly_pipeline CONFIG_BRANCH

---

job-dsls/jobs/prod/prod_rhba_properties_generator.groovy

https://issues.redhat.com/browse/BXMSPROD-1486
<pre>
</pre>

prod_rhba_properties_generator.groovy REPO_URL comment replaced

---

job-dsls/jobs/kie/main/pr_jobs_7_x.groovy

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1785
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1126
<pre>
</pre>

pr_jobs_7_x.groovy build-chain group and branch

---

job-dsls/jobs/kie/main/pr_jobs_7_x.groovy

added PRs for droolsjbpm-knowledge 7.x

---

job-dsls/jobs/prod/prod_kogito_properties_generator.groovy
job-dsls/jobs/prod/prod_rhdm_properties_generator.groovy
job-dsls/jobs/prod/prod_rhpam_properties_generator.groovy
job-dsls/jobs/prod/properties_generator.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1505
Related PRs:
- https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/113
<pre>
</pre>

[BXMSPROD-1505] properties_generator.groovy

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

kogito 1.11.x prod nightly wrong RHBA_MAVEN_REPO_URL fixed

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

updated KIE_PREFIX for daily-build versions

---

jenkins-agents/ansible/kie-rhel.yml

it is basically to get https://github.com/kiegroup/github-action-build-chain/pull/192
<pre>
</pre>

build-chain to 2.3.21

---

job-dsls/jobs/kie/main/deploy_jobs.groovy

[BXMSPROD-1444](https://issues.redhat.com/browse/BXMSPROD-1444)
https://github.com/kiegroup/kie-jenkins-scripts/pull/1153
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1801 
<pre>
</pre>

BXMSPROD-1444: dependencies in downstream repositories

---

job-dsls/jobs/tools/tools_restart_smee_client.groovy

Added the job to restart smee clients.
<pre>
</pre>

jobs: add smee client restart job

---

job-dsls/jobs/tools/tools_restart_smee_client.groovy

Fixes the wrong job description.
<pre>
</pre>

jobs: fix smee client restart description

---

job-dsls/jobs/tools/tools_agent_image_build.groovy
job-dsls/jobs/tools/tools_agent_image_build_PR_test.groovy
job-dsls/jobs/tools/tools_agent_image_sync.groovy
job-dsls/src/main/resources/job-scripts/copyImage.sh

Added jobs for syncing agent images between clouds.
<pre>
</pre>

jobs: add Jenkins agent images sync jobs

---

job-dsls/jobs/kie/main/jenkins_shared_libs.groovy

https://issues.redhat.com/browse/BXMSPROD-1375
<pre>
</pre>

BXMSPROD-1375 Correct Jenkins shared lib PR DSL

---

job-dsls/jobs/kie/main/compile_downstream_build_7_x.groovy

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1807
<pre>
</pre>

[7.59.x] Jenkinsfile.buildchain update

---

jenkins-agents/ansible/kie-rhel.yml
jenkins-agents/ansible/roles/kogito/tasks/main.yml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1808
<pre>
</pre>

build-chain tool removed from jenkins

---

job-dsls/jobs/kie/main/kie_jenkinsScripts_PR.groovy

@mareknovotny made more robust this PR against jdk and mvn version.
This PR failed from time to time because it could not find the right versions. You had to re run it and then it built SUCCESSFUL
<pre>
</pre>

added and fixed existing tool environment variables

---

job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile

Bulk replace RCM guest host URL with download.eng.bos.redhat.com

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

we will use the branch from 7.59.x or whatever the branch we create for RHBA on build-configurations repository
Referenced PRs:
-  https://github.com/kiegroup/kie-jenkins-scripts/pull/1163
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1163
- https://github.com/kiegroup/kogito-pipelines/pull/318
<pre>
</pre>

default_config_branch renamed

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

upgraded KIE_PREFIX

---

job-dsls/jobs/kie/main/communityRelease_pipeline.groovy

added kie to staged repo description

---

job-dsls/jobs/kie/kie-tools/deploy_development_version.groovy
job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy
job-dsls/jobs/kie/kie-tools/kie_docker_ui_webapp.groovy
job-dsls/jobs/kie/kogito/kogito_docs_upload.groovy
job-dsls/jobs/kie/main/automatic_web_publishing.groovy
job-dsls/jobs/kie/main/communityRelease_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk11_prod_pipeline.groovy
job-dsls/jobs/kie/main/dailyBuild_jdk8_pipeline.groovy
job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/deploy_jobs_7_x.groovy
job-dsls/jobs/kie/main/errai_pr.groovy
job-dsls/jobs/kie/main/i18n_translations.groovy
job-dsls/jobs/kie/main/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/kie/main/prodTag_pipeline.groovy
job-dsls/jobs/kie/main/turtleTests.groovy
job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/jobs/seed_jobs/kie_main_branch_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_docs_seed_job.groovy
job-dsls/jobs/seed_jobs/osbs_seed_job.groovy
job-dsls/jobs/seed_jobs/prod_seed_job.groovy
job-dsls/jobs/seed_jobs/tools_seed_job.groovy
job-dsls/jobs/tools/tools_agent_image_build_PR_test.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

fixed tool environment

---

job-dsls/jobs/kie/main/reduced_drools_release.groovy

Reverting Drools reduced release
That job was removed in https://github.com/kiegroup/kie-jenkins-scripts/pull/1149
<pre>
</pre>

reverted removal of reduced_drools_release.groovy

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/jobs/prod/prod_multibranch_nightly.groovy

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1832
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1171
<pre>
</pre>

Temporary Run nightly build on RHOS-01 cloud

---

job-dsls/jobs/osbs/osbs_seed_cloud_jobs.groovy

See: https://issues.redhat.com/browse/KIECLOUD-600
Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>
**JIRA**:  Remove RHDM from OSBS Seed Cloud Jobs.
[link](https://issues.redhat.com/browse/KIECLOUD-600)

[KIECLOUD-600] - Remove RHDM from OSBS Seed Cloud Jobs

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

* https://github.com/kiegroup/kie-jenkins-scripts/pull/1174
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1837
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1838
<pre>
</pre>

RHBA nightly job moved to rhos-01

---

jenkins-agents/ansible/data/config/npm/.npmrc
jenkins-agents/ansible/kie-rhel.yml
jenkins-agents/ansible/roles/kogito/tasks/main.yml
jenkins-agents/ansible/roles/node/tasks/main.yml

https://issues.redhat.com/browse/BXMSPROD-1558
* https://github.com/kiegroup/lock-treatment-tool/pull/1
<pre>
</pre>

[BXMSPROD-1558] @kie scope added

---

job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy

@mareknovotny kie-docker-ci-images and kie-docker-ci will be obsolete - these tests are not any-more needed
etc. 
<pre>
</pre>

removed obsolete docker image

---

job-dsls/jobs/prod/prod_send_umb_message.groovy

prod_send_umb_message.groovy error corrected

---

job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy

removed not anymore existing label

---

job-dsls/jobs/kie/main/communityRelease_pipeline.groovy

Added new engineering managers into email

---

job-dsls/jobs/prod/prod_kogito_staging.groovy
job-dsls/src/main/resources/job-scripts/prod_kogito_staging.jenkinsfile

In order to automatize the kogito staging prod process step
<pre>
</pre>

kogito_staging job

---

job-dsls/jobs/prod/prod_rhsa_errata_content.groovy
job-dsls/src/main/resources/job-scripts/prod_rhsa_errata_content.jenkinsfile

This job generates the content needed when creating the RHSA Errata
https://issues.redhat.com/browse/BXMSPROD-670
https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/181
<pre>
</pre>

[BXMSPROD-670] add rhsa-errata-content job

---

job-dsls/jobs/kie/main/automatic_web_publishing.groovy

because of updates on filemgmg.jboss.org the rsync command had to be modified so the automatic publishing job works again 
<pre>
</pre>

added handshake method to rsync

---

job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy

* sends a notification to kie-ci Zulip channel
* removes leftovers for docker tests
<pre>
</pre>

added sending of notifications to Zulip channel

---

job-dsls/jobs/kie/main/compile_downstream_build.groovy
job-dsls/jobs/kie/main/downstream_pr_jobs.groovy
job-dsls/jobs/kie/main/downstream_production.groovy
job-dsls/jobs/kie/main/upstream.groovy

removed 7.x branch where specified

---

job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_start_jbpm_org.groovy

* https://github.com/kiegroup/kie-jenkins-scripts/pull/1191
* https://github.com/kiegroup/start.jbpm.org/pull/20
<pre>
</pre>

added new update script for start.jbpm.org

---

job-dsls/jobs/kie/kie-tools/upgradeVersions/newBranch_kie_benchmarks.groovy

[BXMSPROD-1576](https://issues.redhat.com/browse/BXMSPROD-1576)
* [kie-jenkins-scripts](https://github.com/kiegroup/kie-jenkins-scripts/pull/1195)
* [kie-benchmarks](https://github.com/kiegroup/kie-benchmarks/pull/159)
<pre>
</pre>

BXMSPROD-1576: added new DSL groovy script for creating new branches

---

job-dsls/build.gradle
job-dsls/jobs/kie/kogito/kogito_tooling_prerelease_branch_UMB_trigger.groovy

**JIRA**: https://issues.redhat.com/browse/BAQE-2206
**referenced Pull Requests**:  
https://github.com/kiegroup/run-tests-with-build/pull/47
<pre>
</pre>
@Ginxo @winklerm Could you please check if this is a correct way to introduce such job? any pointers are welcome

BAQE-2206: Add kogito-tooling-prelease branch trigger

---

job-dsls/jobs/kie/main/jenkins_shared_libs.groovy

cherry-pick: https://github.com/kiegroup/kie-jenkins-scripts/pull/1196

[7.59.x] Update jenkins shared lib PR check (#1196)

---

job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_start_jbpm_org.groovy

- adds red hat product version if needed
https://github.com/kiegroup/kie-jenkins-scripts/pull/1200
https://github.com/kiegroup/start.jbpm.org/pull/22
<pre>
</pre>

added parameter for product versions

---

job-dsls/jobs/kie/main/jenkins_shared_libs.groovy
job-dsls/jobs/prod/prod_multibranch_nightly.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

RHBA multibranch nightly libraryConfiguration credentialsId

---

job-dsls/jobs/prod/prod_create_release_trackers.groovy
job-dsls/src/main/resources/job-scripts/prod_create_release_trackers.jenkinsfile

This job creates creates the release tracker tickets for each release
https://issues.redhat.com/browse/BXMSPROD-1608
<pre>
</pre>

[BXMSPROD-1608] add create_release_trackers job

---

job-dsls/jobs/kie/kogito/kie_tools_prerelease_branch_UMB_trigger.groovy
job-dsls/jobs/seed_jobs/kogito_tools_seed_job.groovy

added seed job for kogito-tooling

---

job-dsls/jobs/kie/kogito/kie_tools_prerelease_branch_UMB_trigger.groovy

better definition for a pipeline trigger.
Tested here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/mbiarnes/job/mbiarnes-seed-job/242/console
<pre>
</pre>

updated pipeline trigger DSL definition

---

job-dsls/jobs/kie/kogito/kogito_docs_upload.groovy

added new email account

---

job-dsls/jobs/kie/kie-tools/upgradeVersions/upgradeAll_kiegroup.groovy

set upstraem for droolsjbpm-build-bootstrap

---

job-dsls/jobs/kie/main/communityRelease_pipeline.groovy

https://github.com/kiegroup/kie-jenkins-scripts/pull/1209
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1892
etc. 
<pre>
</pre>

SAVE DISK SPACE: added sh script to clean-up disk space after building

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

kogito 1.13 prod nightly enabled

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

prod_cron_meta_nightly_pipeline to add drools version

---

job-dsls/jobs/kie/kogito/kie_tools_prerelease_branch_UMB_trigger.groovy

Renames the pre release trigger accordingly to kie-tools changes

Rename kogito-tooling references to kie-tools

---

job-dsls/jobs/kie/main/community_buildchain_pipeline.groovy

New needed scripts/files for the community release pipeline applying the build-chain methodology.
The removal of obsolete scripts will happen this works properly.
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1893
https://github.com/kiegroup/kie-jenkins-scripts/pull/1213
<pre>
</pre>

new job community buildchain pipeline

---

job-dsls/jobs/kie/kogito/kie_tools_prerelease_branch_UMB_trigger.groovy

Fixes missing escape of character in message content @mbiarnes

Fix typo in messageContent of kie-tools prerelease trigger

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

prod_cron_meta_nightly_pipeline kogito 1.13.x updated

---

job-dsls/jobs/kie/main/community_buildchain_pipeline.groovy

Th URL for additional test in the new community release pipeline had to be fixed adding a missing part
<pre>
</pre>

fixed URL for additional test

---

job-dsls/jobs/kie/kogito/kie_tools_prerelease_branch_UMB_trigger.groovy
job-dsls/jobs/seed_jobs/kogito_tools_seed_job.groovy

[BXMSPROD-1655](https://issues.redhat.com/browse/BXMSPROD-1655)
<pre>
</pre>

BXMSPROD-1655: refactored kie_tools_prerelease_branch_UMB_trigger.groovy

---

job-dsls/jobs/kie/main/dailyBuild_jdk11_pipeline.groovy

**Thank you for submitting this pull request** 
<pre>
</pre>

removed additional test for docker-image since it is absolete now

---

job-dsls/jobs/prod/prod_create_images_templates_and_sources.groovy
job-dsls/src/main/resources/job-scripts/prod_create_images_templates_and_sources.jenkinsfile

This job creates the OpenShift images templates and sources
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1666
<pre>
</pre>

[BXMSPROD-1666] add create-images-templates-and-sources job

---

job-dsls/jobs/kie/main/community_buildchain_pipeline.groovy

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1913
https://github.com/kiegroup/kie-jenkins-scripts/pull/1227
<pre>
</pre>

fixes of parameter-values

---

job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy

upgraded meta_pipeline to trigger also 7.67.x daily builds

---

job-dsls/jobs/kie/kie-tools/upgradeVersions/kie_meta_upgrade_pipeline.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/upgradeAll_kiegroup.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_kie_benchmarks.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_kie_cloud_tests.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_kie_prefix.groovy
job-dsls/jobs/kie/main/community_buildchain_pipeline.groovy

replaced rhos-d by rhos-01

---

job-dsls/jobs/kie/main/community_buildchain_pipeline.groovy

re-established value for community release NEXUS_URL

---

job-dsls/jobs/prod/prod_rhba_stage_cpaas_artifacts.groovy
job-dsls/src/main/resources/job-scripts/prod_rhba_stage_cpaas_artifacts.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1667
<pre>
</pre>

[BXMSPROD-1667] add stage-cpaas-artifacts job

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

kogito 1.13.x rhba nexus repository to next_product

---

job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy

disabled daily builds for 7.59.x

---

job-dsls/jobs/kie/main/jbpm_web_publishing.groovy

the former filemgmt server is for rsync commands now filemgmt-prod-sync.jboss.org with port 2222
etc. 
<pre>
</pre>

changed server name for publishing website

---

job-dsls/jobs/kie/kogito/kogito_docs_upload.groovy

stabilized kogito-docs-upload

---

job-dsls/jobs/seed_jobs/kogito_docs_seed_job.groovy

enabled seed job for kogito-docs-upload

---

job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy
job-dsls/jobs/kie/main/daily_builds.groovy

daily-build jdk11 for prod [-Dproductized] for main and 7.67.x will not run anymore.
etc. 
<pre>
</pre>

disabled community daily builds for prod

---

job-dsls/jobs/kie/main/jbpm_web_publishing.groovy

https://github.com/kiegroup/jbpm-website/pull/195
https://github.com/kiegroup/kie-jenkins-scripts/pull/1244
<pre>
</pre>

refactored jbpm-website auto publishing job

---

job-dsls/jobs/prod/prod_rhpam_properties_generator.groovy

https://issues.redhat.com/browse/BXMSPROD-1691
<pre>
</pre>

[BXMSPROD-1691] add BOM_VERSION input parameter to rhpam-properties-generator job

---

job-dsls/jobs/kie/kie-tools/upgradeVersions/kie_meta_upgrade_pipeline.groovy

new 7.x branch in kie-benchmarks

---

.github/workflows/pull_request.yml

Pull Request GHA flow

---

job-dsls/jobs/prod/prod_move_jiras_qa.groovy
job-dsls/src/main/resources/job-scripts/prod_move_jiras_qa.jenkinsfile

https://issues.redhat.com/browse/BXMSPROD-1721
<pre>
</pre>

[BXMSPROD-1721] add move-jiras-qa job

---

job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy

job name was changed - so seed job fails. This was fixed here.
etc. 
<pre>
</pre>

fixed groovy script name

---

job-dsls/jobs/kie/kogito/kogito_docs_upload.groovy

https://github.com/kiegroup/kie-jenkins-scripts/pull/1257
https://github.com/kiegroup/kie-docs/pull/4223
<pre>
</pre>

fixed path for rsync

---

job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

Generate Data Daily Jobs 7.67.x

---

job-dsls/jobs/kie/main/compile_downstream_build.groovy
job-dsls/jobs/kie/main/compile_downstream_build_7_x.groovy
job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/deploy_jobs_7_x.groovy
job-dsls/jobs/kie/main/downstream_pr_jobs.groovy
job-dsls/jobs/kie/main/downstream_pr_jobs_7_x.groovy
job-dsls/jobs/kie/main/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/kie/main/pr_jobs.groovy
job-dsls/jobs/kie/main/pr_jobs_7_x.groovy
job-dsls/jobs/kie/main/turtleTests.groovy
job-dsls/jobs/seed_jobs/kie_main_branch_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_docs_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/osbs_seed_job.groovy
job-dsls/jobs/seed_jobs/prod_seed_job.groovy

master node is excluded in all places where I think it could be the value of `label`
etc. 
<pre>
</pre>

excluded explicitly master node

---

job-dsls/jobs/prod/prod_rhpam_properties_generator.groovy

* https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/167
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1980
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1261
<pre>
</pre>

rhpam_properties_generator FILE_ID inputs

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

* https://github.com/kiegroup/kie-jenkins-scripts/pull/1260
<pre>
</pre>

7.67.x-blue/1.13.x-blue nightly 1.13.0-blue

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

* https://github.com/kiegroup/kie-jenkins-scripts/pull/1262
<pre>
</pre>

7.67.x-blue/1.13.x-blue nightly 1.13.2-blue

---

job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_business_central.groovy

[BXMSPROD-1545](https://issues.redhat.com/browse/BXMSPROD-1545)
* [referenced pull request 1](https://github.com/jboss-dockerfiles/business-central/pull/95)
* [referenced pull request 2](https://github.com/kiegroup/kie-jenkins-scripts/pull/1269)
<pre>
</pre>

BXMSPROD-1545: DSL job for upgrading business-central images

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Fixed the '-' character illegal in UMB topic name.
<pre>
</pre>

prod nightly meta pipeline: fix UMB topic format for blue

---

job-dsls/jobs/prod/prod_kogito_properties_generator.groovy

* https://github.com/kiegroup/kie-jenkins-scripts/pull/1272
* https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/170
* https://github.com/kiegroup/kogito-pipelines/pull/517
<pre>
</pre>

[kogito][1.13-blue] properties files

---

job-dsls/jobs/prod/prod_bamoe_staging.groovy
job-dsls/src/main/resources/job-scripts/prod_bamoe_staging.jenkinsfile

I've created a temp job here to test it https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/PROD/job/rhba-staging-bamoe

Add BAMOE staging job and fix potential bug in current rhba staging job

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrDroolsjbpmToolsJob.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

(cherry picked from commit 5cfee4e280f0d60ab23f9bf9fb0b7b8d275dd0d2)
etc. 
<pre>
</pre>

missing trigger phrase in kie-docs PRs

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/468
- https://github.com/kiegroup/kogito-runtimes/pull/2244
- https://github.com/kiegroup/kogito-examples/pull/1279
- https://github.com/jboss-integration/kogito-rhba/pull/32
- https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/175
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1279
- https://github.com/kiegroup/kogito-pipelines/pull/557

BAPL-2291 Remove OptaPlanner Workbench

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

-blue removed from UMB_VERSION serverless-logic

---

job-dsls/jobs/kie/main/compile_downstream_build.groovy
job-dsls/jobs/kie/main/downstream_pr_jobs.groovy

added missing reps for FDBs and CDBs

---

job-dsls/jobs/kie/main/deploy_jobs.groovy

added missing deploy jobs
etc. 
<pre>
</pre>

added missing repos for deploy jobs

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

changed Constant to fetch the right jdk version

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1771
<pre>
</pre>

[BXMSPROD-1771] add osl-trigger-umb-message job

---

job-dsls/jobs/kie/kogito/kie_tools_prerelease_branch_UMB_trigger.groovy

moved cleanWs() to be the last action

---

job-dsls/jobs/kie/main/daily_builds.groovy

changed jdk version for daily build

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

with this change, all jobs using the Constants are updated to this jdk version
etc. 
<pre>
</pre>

changed JDK_VERSION in Constants to 11.0.15

---

job-dsls/jobs/prod/prod_pr_jobs.groovy

**JIRA**:   https://issues.redhat.com/browse/BXMSPROD-1796
<pre>
</pre>

[BXMSPROD-1796] add PR CI for jboss-integration/rhba repository

---

job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1796
<pre>
</pre>

[BXMSPROD-1796] setup Nexus repository group as rhba-7.13-nightly

---

job-dsls/jobs/kie/main/downstream_production.groovy

downstream_production: enable full downstream build for jboss-integration projects

---

job-dsls/jobs/kie/main/downstream_production.groovy

downstream_production: update droolsjbpm-build-bootstrap url to be a fixed url

---

.gitignore
job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Corresponding to https://github.com/kiegroup/kie-jenkins-scripts/blob/main/job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy#L34

Correct OSL main branch version

---

job-dsls/jobs/kie/main/downstream_production.groovy

buildChainGroup default value for downstream_production.groovy

---

job-dsls/src/main/resources/job-scripts/prod_bamoe_staging.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_staging.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1795
<pre>
</pre>

[BXMSPROD-1795] Remove reference-implementation zip from staging job

---

job-dsls/jobs/prod/prod_move_jiras_qa.groovy
job-dsls/src/main/resources/job-scripts/prod_move_jiras_qa.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1256
<pre>
</pre>

[BXMSPROD-1256] remove cutoff date parameter from prod_move_jiras_qa.groovy

---

job-dsls/jobs/prod/prod_kogito_stage_cpaas_artifacts.groovy
job-dsls/src/main/resources/job-scripts/prod_kogito_stage_cpaas_artifacts.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1801
<pre>
</pre>

[BXMSPROD-1801] add kogito-stage-cpaas-artifacts job

---

job-dsls/jobs/kie/main/errai_jdk8_pr.groovy

errai PRs for jdk11 and jdk8

---

job-dsls/jobs/kie/main/errai_pr.groovy

fixed owners and commit status context

---

job-dsls/jobs/kie/main/compile_downstream_build.groovy
job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/downstream_pr_jobs.groovy
job-dsls/jobs/kie/main/downstream_production.groovy
job-dsls/jobs/kie/main/pr_jobs.groovy

**JIRA**:
- https://issues.redhat.com/browse/BXMSPROD-1763
**referenced Pull Requests** (backports): 
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1315
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1316
Cleanup of the `jbpm-designer` repository
<pre>
</pre>

jbpm-designer repo cleanup

---

job-dsls/jobs/kie/main/compile_downstream_build.groovy
job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/downstream_pr_jobs.groovy
job-dsls/jobs/kie/main/downstream_production.groovy
job-dsls/jobs/kie/main/pr_jobs.groovy

**JIRA**:
- https://issues.redhat.com/browse/BXMSPROD-1763
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1314
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1316
<pre>
</pre>

[7.67.x] Jbpm designer removal

---

job-dsls/jobs/kie/main/compile_downstream_build.groovy
job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/downstream_pr_jobs.groovy
job-dsls/jobs/kie/main/downstream_production.groovy
job-dsls/jobs/kie/main/pr_jobs.groovy

**JIRA**:
- https://issues.redhat.com/browse/BXMSPROD-1763
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1314
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1315
<pre>
</pre>

[7.67.x-blue] jbpm-designer removal

---

job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

related to https://issues.redhat.com/browse/SPMM-11027
etc. 
<pre>
</pre>

prod_osl_trigger_umb_message: update staged artifacts path to rhoss/rhoss-logic folder

---

job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1806
<pre>
</pre>

[BXMSPROD-1806] fix osl-trigger-umb-message job when getting milestones from PNC

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1807
<pre>
</pre>

[BXMSPROD-1807] add Quarkus version to the osl-trigger-umb-message job

---

job-dsls/src/main/resources/job-scripts/prod_kogito_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_stage_cpaas_artifacts.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1808
<pre>
</pre>

[BXMSPROD-1808] Generate maven-repository.text file when staging CPaaS artifacts

---

job-dsls/jobs/prod/prod_create_images_templates_and_sources.groovy
job-dsls/jobs/prod/prod_kogito_create_images_sources.groovy

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1805
Related Pull Requests:
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1324
Fixed default value and description for Kogito container sources generation.
<pre>
</pre>

[BXMSPROD-1805] Fixed description and default value for kogito images sources generation

---

job-dsls/jobs/kie/kogito/kogito_docs_upload.groovy

for a better understanding which have to be the used versions in parameters
<pre>
</pre>

fixes in kogito docs job

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/jobs/prod/prod_multibranch_nightly.groovy

**JIRA**:
- https://issues.redhat.com/browse/BXMSPROD-1826
- https://github.com/kiegroup/optaplanner/pull/2214
<pre>
</pre>

[RHBOP] [BXMSPROD-1826] Added multibranch nightly job for Red Hat Build of Optaplanner

---

job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

**JIRA**:
- https://issues.redhat.com/browse/BXMSPROD-1826
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1327
- https://github.com/kiegroup/optaplanner/pull/2214
<pre>
</pre>

Added rhbop.nightly in productization jobs status page

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1826
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1327
- https://github.com/kiegroup/optaplanner/pull/2214
Fixed _isMainBranchVersion_ for RHBOP.
<pre>
</pre>

[RHBOP] Fixed main branch version

---

job-dsls/jobs/kie/main/compile_downstream_build.groovy
job-dsls/jobs/kie/main/compile_downstream_build_7_x.groovy
job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/deploy_jobs_7_x.groovy
job-dsls/jobs/kie/main/downstream_pr_jobs.groovy
job-dsls/jobs/kie/main/downstream_pr_jobs_7_x.groovy
job-dsls/jobs/kie/main/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/kie/main/pr_jobs.groovy
job-dsls/jobs/kie/main/pr_jobs_7_x.groovy
job-dsls/jobs/kie/main/srcclr_scan_job.groovy
job-dsls/jobs/kie/main/srcclr_scan_pipeline.groovy
job-dsls/jobs/kie/main/turtleTests.groovy
job-dsls/jobs/prod/prod_replace_shared_libraries.groovy
job-dsls/jobs/prod/prod_rhba_prod_branch.groovy
job-dsls/jobs/prod/prod_rhba_replace_version.groovy
job-dsls/jobs/seed_jobs/kie_main_branch_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_new_branches_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_docs_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/osbs_seed_job.groovy
job-dsls/jobs/seed_jobs/prod_seed_job.groovy

changed label master to built-in

---

job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

Expose main branch for productized nightly jobs

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmContainerTestMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmTestCoverageMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieServerMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieWbTestMatrix.groovy
job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_create_release_trackers.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_create_images_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_move_jiras_qa.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_stage_cpaas_artifacts.jenkinsfile

[main] changed leftover !master labels to !built-in

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmContainerTestMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmTestCoverageMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieServerMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieWbTestMatrix.groovy
job-dsls/src/main/resources/job-scripts/prod_create_release_trackers.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile

[7.67.x] changed leftover !master labels to !built-in

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmContainerTestMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmTestCoverageMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieServerMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieWbTestMatrix.groovy
job-dsls/src/main/resources/job-scripts/prod_create_release_trackers.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile

[7.67.x-blue] changed leftover !master labels to !built-in

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

**JIRA**:
- https://issues.redhat.com/browse/BXMSPROD-1847
etc. 
<pre>
</pre>

[BXMSPROD-1847] Added image brew tag for data-index-ephemeral

---

job-dsls/jobs/prod/prod_rhbop_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhbop_trigger_umb_message.jenkinsfile

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1843
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/220
Fixes:
- Add new job for `RHBOP` product aiming to compute and send the UMB message to QE.
- UMB trigger jobs refactoring in order to use newly exposed `pnc` lib (see https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/220)
> Note: once https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/220 will be merged, we can merge this too.
<pre>
</pre>

[BXMSPROD-1843] RHBOP UMB Message Job

---

job-dsls/jobs/prod/prod_create_release_trackers.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1851
<pre>
</pre>

[BXMSPROD-1851] add rhbop template for create-release-trackers job

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1849
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1342
<pre>
</pre>

[RHBOP] Update main nightly version to 8.30.0

---

job-dsls/src/main/resources/job-scripts/prod_rhbop_trigger_umb_message.jenkinsfile

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1860
<pre>
</pre>

[BXMSPROD-1860] Fixed artifacts filenames

---

job-dsls/src/main/resources/job-scripts/prod_rhbop_stage_cpaas_artifacts.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1860
<pre>
</pre>

[BXMSPROD-1860] adjust rhbop artifacts name in rhbop-stage-cpaas-artifacts job

---

job-dsls/src/main/resources/job-scripts/prod_rhbop_stage_cpaas_artifacts.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1860
<pre>
</pre>

[BXMSPROD-1860] fix maven repository name when generating maven repository text file

---

job-dsls/jobs/prod/prod_move_jiras_qa.groovy
job-dsls/src/main/resources/job-scripts/prod_move_jiras_qa.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1867
<pre>
</pre>

[BXMSPROD-1867] add support for BAMOE product

---

job-dsls/jobs/prod/prod_move_jiras_qa.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1859
<pre>
</pre>

[BXMSPROD-1859] add support for RHBOP product on move-jiras-qa job

---

job-dsls/jobs/prod/prod_create_release_trackers.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1877
<pre>
</pre>

[BXMSPROD-1877] add bamoe_kogito template for create-release-trackers job

---

job-dsls/jobs/kie/main/jbake_web_publishing.groovy

https://issues.redhat.com/browse/KOGITO-8216
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/687
- https://github.com/kiegroup/drools-website/pull/230
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1362

Web publishing: Remove Drools Website

---

job-dsls/jobs/seed_jobs/kie_main_branch_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_docs_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_tools_seed_job.groovy

remove jobs that are not anymore built via dsl

---

job-dsls/jobs/kie/main/pr_jobs.groovy

**JIRA**:
- https://issues.redhat.com/browse/BXMSPROD-1862
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1351
- https://github.com/jboss-integration/rhbop-optaplanner/pull/6
<pre>
</pre>

[RHBOP] Registered rhbop-optaplanner for PR checks jenkins job

---

job-dsls/jobs/prod/prod_bamoe_kogito_stage_cpaas_artifacts.groovy
job-dsls/src/main/resources/job-scripts/prod_bamoe_kogito_stage_cpaas_artifacts.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1883
<pre>
</pre>

[BXMSPROD-1883] add bamoe-kogito-stage-cpaas-artifacts job

---

job-dsls/jobs/prod/prod_kogito_properties_generator.groovy

[BXMSPROD-1885] fix typo in kogito-properties-generator job parameters

---

job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

generate-data to nodejs-16.2.0

---

job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

prod_osl_trigger_umb_message: remove extra breakline after image tag

---

job-dsls/jobs/prod/prod_rhpam_properties_generator.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1889
Related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2136
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1374
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/225
<pre>
</pre>

[BXMSPROD-1889] add TAG_HASH property to rhpam-properties-generator job

---

job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

remove kogito.nightly status for 1.30.x

---

job-dsls/jobs/kie/branch/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/kie/branch/pr_jobs.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/kie_meta_upgrade_pipeline.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_kie_prefix.groovy
job-dsls/jobs/seed_jobs/kie_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_docs_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/osbs_seed_job.groovy
job-dsls/jobs/seed_jobs/prod_seed_job.groovy

main: https://github.com/kiegroup/kie-jenkins-scripts/pull/1383
7.67.x: https://github.com/kiegroup/kie-jenkins-scripts/pull/1384
7.67.x-blue: https://github.com/kiegroup/kie-jenkins-scripts/pull/1385
<pre>
</pre>

BXMSPROD-1927: rename kie-jenkins-scripts to kie-ci

---

job-dsls/jobs/kie/branch/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/kie/branch/pr_jobs.groovy
job-dsls/jobs/seed_jobs/kie_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/osbs_seed_job.groovy
job-dsls/jobs/seed_jobs/prod_seed_job.groovy

main: https://github.com/kiegroup/kie-jenkins-scripts/pull/1383
7.67.x: https://github.com/kiegroup/kie-jenkins-scripts/pull/1384
7.67.x-blue: https://github.com/kiegroup/kie-jenkins-scripts/pull/1385
<pre>
</pre>

BXMSPROD-1927: rename kie-jenkins-scripts repository to kie-ci

---

job-dsls/jobs/osbs/osbs_seed_cloud_jobs.groovy

Signed-off-by: Your Name <fspolti@redhat.com>
etc. 
<pre>
</pre>

[KIECLOUD-658] - Delete rhdm jobs from pipeline

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1940
<pre>
</pre>

[BXMSPROD-1940] add QUARKUS_VERSION parameter in osl-trigger-umb-message job

---

job-dsls/jobs/kie/branch/community_buildchain_pipeline.groovy
job-dsls/jobs/kie/branch/daily_builds.groovy

env prefix doesn't work always

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmContainerTestMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmTestCoverageMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieServerMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieWbTestMatrix.groovy

fixed additional tests

---

job-dsls/jobs/kie/branch/daily_builds.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

various fixes for additional tests

---

job-dsls/jobs/kie/branch/daily_builds.groovy
job-dsls/jobs/kie/kie-tools/kieAll_meta_pipeline.groovy

re-enabled main PROD community daily build

---

job-dsls/jobs/kie/branch/daily_builds.groovy

[7.67.x] removed daily builds for production

---

job-dsls/jobs/kie/branch/daily_builds.groovy

(cherry picked from commit 54d3bd6bee2f4a3f3d93debf246f8b065c1d2714)
etc. 
<pre>
</pre>

[7.67.x-blue] removed daily builds for production

---

job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

added community upstream prod build

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1945
- https://github.com/kiegroup/optaplanner/pull/2503
- https://github.com/kiegroup/kie-ci/pull/1408
<pre>
</pre>

[BXMSPROD-1945] Set empty next drools and product version

---

job-dsls/jobs/kie/branch/compile_downstream_build.groovy
job-dsls/jobs/kie/branch/compile_downstream_build_7_x.groovy
job-dsls/jobs/kie/branch/downstream_pr_jobs.groovy
job-dsls/jobs/kie/branch/downstream_pr_jobs_7_x.groovy
job-dsls/jobs/kie/branch/downstream_production.groovy
job-dsls/jobs/kie/branch/downstream_production_7_x.groovy
job-dsls/jobs/kie/branch/errai_jdk8_pr.groovy
job-dsls/jobs/kie/branch/errai_pr.groovy
job-dsls/jobs/kie/branch/pr_jobs.groovy
job-dsls/jobs/kie/branch/pr_jobs_7_x.groovy
job-dsls/jobs/kie/branch/prodProjects_downstream_production.groovy
job-dsls/jobs/kie/branch/srcclr_scan_job.groovy
job-dsls/jobs/kie/branch/srcclr_scan_pipeline.groovy
job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/prod/prod_bamoe_kogito_properties_generator.groovy
job-dsls/jobs/prod/prod_bamoe_kogito_stage_cpaas_artifacts.groovy
job-dsls/jobs/prod/prod_bamoe_properties_generator.groovy
job-dsls/jobs/prod/prod_bamoe_stage_cpaas_artifacts.groovy
job-dsls/jobs/prod/prod_create_images_templates_and_sources.groovy
job-dsls/jobs/prod/prod_create_release_trackers.groovy
job-dsls/jobs/prod/prod_kogito_create_images_sources.groovy
job-dsls/jobs/prod/prod_kogito_properties_generator.groovy
job-dsls/jobs/prod/prod_kogito_stage_cpaas_artifacts.groovy
job-dsls/jobs/prod/prod_multibranch_nightly.groovy
job-dsls/jobs/prod/prod_rhba_stage_cpaas_artifacts.groovy
job-dsls/jobs/prod/prod_rhbop_stage_cpaas_artifacts.groovy
job-dsls/jobs/prod/prod_rhpam_properties_generator.groovy
job-dsls/jobs/prod/properties_generator.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

Added more constraints (number of days to keep a job build) or lowered the number of builds to keep in order to maintain free disk space.
<pre>
</pre>

Add more constraints to build retention

---

job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Signed-off-by: Spolti <fspolti@redhat.com>
etc. 
<pre>
</pre>

[KIECLOUD-680] - Update the osbs-builder label to the new ones

---

job-dsls/jobs/kie/branch/compile_downstream_build.groovy
job-dsls/jobs/kie/branch/downstream_pr_jobs.groovy
job-dsls/jobs/kie/branch/downstream_production.groovy
job-dsls/jobs/kie/branch/pr_jobs.groovy
job-dsls/jobs/kie/branch/prodProjects_downstream_production.groovy
job-dsls/jobs/kie/branch/srcclr_scan_job.groovy
job-dsls/jobs/kie/branch/srcclr_scan_pipeline.groovy
job-dsls/jobs/prod/prod_kogito_properties_generator.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

Added more constraints (number of days to keep a job build) or lowered the number of builds to keep in order to maintain free disk space.
<pre>
</pre>

[7.67.x-blue] Add more constraints to build retention (#1411)

---

job-dsls/jobs/kie/branch/compile_downstream_build.groovy
job-dsls/jobs/kie/branch/downstream_pr_jobs.groovy
job-dsls/jobs/kie/branch/downstream_production.groovy
job-dsls/jobs/kie/branch/pr_jobs.groovy
job-dsls/jobs/kie/branch/prodProjects_downstream_production.groovy
job-dsls/jobs/kie/branch/srcclr_scan_job.groovy
job-dsls/jobs/kie/branch/srcclr_scan_pipeline.groovy
job-dsls/jobs/prod/prod_kogito_properties_generator.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

Added more constraints (number of days to keep a job build) or lowered the number of builds to keep in order to maintain free disk space.
<pre>
</pre>

[7.67.x] Add more constraints to build retention (#1411)

---

job-dsls/src/main/resources/job-scripts/prod_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_create_release_trackers.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_create_images_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_move_jiras_qa.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1957
<pre>
</pre>

[BXMSPROD-1957] use rhba-prod python virtual env for jobs that invoke python script

---

job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy

Signed-off-by: Spolti <fspolti@redhat.com>
etc. 
<pre>
</pre>

[KIECLOUD-665] - add dashbuilder component

---

job-dsls/jobs/kie/branch/daily_builds.groovy

[7.67.x] missing parameter

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrVerificationJob.groovy

[main](https://github.com/kiegroup/kie-ci/pull/1427)
[7.67.x](https://github.com/kiegroup/kie-ci/pull/1428)
[7.67.x-blue](https://github.com/kiegroup/kie-ci/pull/1429)
<pre>
</pre>

added missing params

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

- https://github.com/kiegroup/optaplanner/pull/2556
<pre>
</pre>

Downgrade drools product version to 8.29.0 for RHBOP 8.33

---

job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy

Signed-off-by: Spolti <fspolti@redhat.com>
etc. 
<pre>
</pre>

[KIECLOUD-685] - Organize the jobs into different directories

---

job-dsls/jobs/kie/branch/kie_docs_pr.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrKieDocsJob.groovy

(cherry picked from commit 1a0c90c4519c39112f9a11c3f686669a94fe2872)
[main](https://github.com/kiegroup/kie-ci/pull/1431)
[7.67.x](https://github.com/kiegroup/kie-ci/pull/1432)
[7.67.x-blue](https://github.com/kiegroup/kie-ci/pull/1433)
<pre>
</pre>

[7.67.x] zipped the archived artifacts for kie-docs

---

job-dsls/jobs/kie/branch/kie_docs_pr.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrKieDocsJob.groovy

[main](https://github.com/kiegroup/kie-ci/pull/1431)
[7.67.x](https://github.com/kiegroup/kie-ci/pull/1432)
[7.67.x-blue](https://github.com/kiegroup/kie-ci/pull/1433)
<pre>
</pre>

zipped the archived artifacts for kie-docs

---

job-dsls/jobs/kie/branch/kie_docs_pr.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrKieDocsJob.groovy

(cherry picked from commit 1a0c90c4519c39112f9a11c3f686669a94fe2872)
[main](https://github.com/kiegroup/kie-ci/pull/1431)
[7.67.x](https://github.com/kiegroup/kie-ci/pull/1432)
[7.67.x-blue](https://github.com/kiegroup/kie-ci/pull/1433)
<pre>
</pre>

[7.67.x-blue] zipped the archived artifacts for kie-docs

---

job-dsls/jobs/osbs/operators_osbs_seed_cloud_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Signed-off-by: Davide Salerno <dsalerno@redhat.com>
**JIRA**: [link](https://issues.redhat.com/browse/KIECLOUD-677)
<pre>
</pre>

[KIECLOUD-677] Create a new Jenkins seed job for operators

---

job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy

Signed-off-by: Spolti <fspolti@redhat.com>
etc. 
<pre>
</pre>

[KIECLOUD-683] - Find a way to retrieve the image name built os OSBS

---

job-dsls/jobs/kie/kogito/kie_tools_prerelease_branch_UMB_trigger.groovy

**JIRA**: 
[BAQE-2503](https://issues.redhat.com/browse/BAQE-2503)
@mbiarnes updating the message to new value, QE jobs already expect this

BAQE-2503: Update the UMB message for kie-tools to be more generic

---

job-dsls/jobs/osbs/operators_osbs_seed_cloud_jobs.groovy

See:https://issues.redhat.com/browse/KIECLOUD-663
Signed-off-by: desmax74 <mdessi@redhat.com>
**JIRA**:(https://issues.redhat.com/browse/KIECLOUD-663)

[KIECLOUD-663] Create pipeline for rhpam-kogito operator

---

job-dsls/jobs/kie/branch/deploy_jobs_7_x.groovy
job-dsls/jobs/kie/branch/pr_jobs_7_x.groovy
job-dsls/jobs/kie/branch/sonarcloud_daily.groovy

[droolsjbpm-build-bootstrap](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2219)
[kie-ci](https://github.com/kiegroup/kie-ci/pull/1439)
<pre>
</pre>

[main] removed optawebs* repos

---

job-dsls/jobs/kie/branch/compile_downstream_build.groovy
job-dsls/jobs/kie/branch/deploy_jobs.groovy
job-dsls/jobs/kie/branch/downstream_pr_jobs.groovy
job-dsls/jobs/kie/branch/pr_jobs.groovy
job-dsls/jobs/kie/branch/sonarcloud_daily.groovy

remove optawebs* from 7.67.x

---

job-dsls/jobs/osbs/bamoe_operators_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_operators_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy

[KIECLOUD-688] - Add docker to the OSBS builder on Jenkins

---

job-dsls/jobs/osbs/bamoe_operators_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_operators_osbs_seed_cloud_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

**JIRA**: 
[KIECLOUD-677](https://issues.redhat.com/browse/KIECLOUD-677)
* [kie-cloud-operator/856](https://github.com/kiegroup/kie-cloud-operator/pull/856)
* [kie-cloud-operator/857](https://github.com/kiegroup/kie-cloud-operator/pull/857)
<pre>
</pre>

KIECLOUD-677 - Create a new Jenkins seed job for operators /2

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/jobs/prod/prod_multibranch_nightly.groovy
job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

**JIRA**:
https://issues.redhat.com/browse/BXMSPROD-1981
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/267
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/15/
- https://github.com/kiegroup/kie-ci/pull/1450
<pre>
</pre>

[BXMSPROD-1981] added drools ansible rulebook nightly

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Fixing missed parameter
**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1981
- https://github.com/kiegroup/kie-ci/pull/1450 
<pre>
</pre>

[BXMSPROD-1981] added DEFINITION_FILE_OWNER param

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/jobs/prod/prod_multibranch_nightly.groovy
job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1981
etc. 
<pre>
</pre>

Renamed rulebook to drools-ansible-integration

---

job-dsls/jobs/osbs/bamoe_operators_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_operators_osbs_seed_cloud_jobs.groovy

[KIECLOUD-698] - Retrieve the image name built os OSBS for the operators

---

job-dsls/jobs/osbs/rhpam_kogito_images_osbs_seed_cloud_jobs.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

[KIECLOUD-661] - Create pipeline for rhpam-kogito images

---

job-dsls/jobs/osbs/rhpam_kogito_images_osbs_seed_cloud_jobs.groovy

[KIECLOUD-661] - small typo fix

---

job-dsls/jobs/osbs/kogito_osbs_build_pipeline.jenkinsfile
job-dsls/jobs/osbs/kogito_osbs_build_pipeline_jobdsl.groovy
job-dsls/jobs/osbs/osbs_build_pipeline.jenkinsfile
job-dsls/jobs/osbs/osbs_build_pipeline_jobdsl.groovy

**JIRA**: 
[KIECLOUD-691](https://issues.redhat.com/browse/KIECLOUD-691)

KIECLOUD-691 - Create stages to run the build image jobs

---

job-dsls/jobs/osbs/kogito_osbs_build_pipeline.jenkinsfile
job-dsls/jobs/osbs/osbs_build_pipeline.jenkinsfile

fix typos in osbs_build_pipeline.jenkinsfile

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1983
* https://github.com/kiegroup/optaplanner/pull/2717
* https://github.com/kiegroup/kie-ci/pull/1463
<pre>
</pre>

[BXMSPROD-1983] migrate RHBOP nigthly to build-chain

---

job-dsls/jobs/osbs/kogito_osbs_build_pipeline.jenkinsfile
job-dsls/jobs/osbs/kogito_osbs_build_pipeline_jobdsl.groovy
job-dsls/jobs/osbs/osbs_build_pipeline.jenkinsfile
job-dsls/jobs/osbs/osbs_build_pipeline_jobdsl.groovy

[KIECLOUD-689](https://issues.redhat.com/browse/KIECLOUD-689)
etc. 
<pre>
</pre>

OSBS build pipeline - fix git url and UMB topic

---

job-dsls/jobs/osbs/bamoe_kogito_images_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_kogito_images_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy

[KIECLOUD-695] - Execute the behave tests after the build

---

job-dsls/jobs/prod/prod_bamoe_properties_generator.groovy
job-dsls/jobs/prod/prod_rhpam_properties_generator.groovy

**JIRA**: https://issues.redhat.com/browse/RHPAM-4642
<pre>
</pre>

[RHPAM-4642] update default MVEL_VERSION parameter value for rhpam and bamoe properties generator jobs

---

job-dsls/jobs/prod/prod_create_images_templates_and_sources.groovy
job-dsls/jobs/prod/prod_kogito_create_images_sources.groovy
job-dsls/src/main/resources/job-scripts/prod_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_create_images_sources.jenkinsfile

**JIRA**:  https://issues.redhat.com/browse/BXMSPROD-2014
<pre>
</pre>

[BXMSPROD-2014] allow uploading artifacts to rcm-host in create-images-templates-and-sources and kogito-create-images-sources jobs

---

job-dsls/src/main/resources/job-scripts/prod_bamoe_kogito_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_bamoe_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhbop_stage_cpaas_artifacts.jenkinsfile

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-2015
etc. 
<pre>
</pre>

[BXMSPROD-2015] Adapt zip/unzip usage on spmm-utils

---

job-dsls/jobs/prod/prod_bamoe_create_images_templates_and_sources.groovy
job-dsls/jobs/prod/prod_bamoe_kogito_create_images_sources.groovy
job-dsls/src/main/resources/job-scripts/prod_bamoe_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_bamoe_kogito_create_images_sources.jenkinsfile

**JIRA**:  https://issues.redhat.com/browse/BXMSPROD-2017
<pre>
</pre>

[BXMSPROD-2017] add bamoe-create-images-templates-and-sources and bamoe-kogito-create-images-sources jobs

---

job-dsls/src/main/resources/job-scripts/prod_bamoe_kogito_create_images_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_create_images_sources.jenkinsfile

fix typo in stage name in kogito-create-images-sources and bamoe-kogito-create-images-sources jobs

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieWbTestMatrix.groovy

[main] firefox upgrade

---

job-dsls/jobs/kie/branch/daily_builds.groovy

[7.67.x-blue] upgrade EAP to 7.4.10

---

job-dsls/jobs/kie/branch/daily_builds.groovy

[7.67.x] upgrade EAP to 7.4.10

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1984
<pre>
</pre>

[BXMSPROD-1984] add parameter for Drools prod version in osl-trigger-umb-message job

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

[DAI] nightly: take product and drools version from pom

---

job-dsls/jobs/prod/prod_bamoe_create_images_templates_and_sources.groovy
job-dsls/jobs/prod/prod_bamoe_kogito_create_images_sources.groovy
job-dsls/jobs/prod/prod_create_images_templates_and_sources.groovy
job-dsls/jobs/prod/prod_kogito_create_images_sources.groovy

update builds parameter description in images templates and sources jobs

---

job-dsls/jobs/kie/branch/community_buildchain_pipeline.groovy

minor: changed wording

---

job-dsls/jobs/prod/prod_send_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_bamoe_staging.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_staging.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhsa_errata_content.jenkinsfile

Specify nodes for node pipelines

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Upgrade next BAMOE product version to 8.0.4

---

job-dsls/jobs/prod/prod_bamoe_kogito_properties_generator.groovy
job-dsls/jobs/prod/prod_kogito_properties_generator.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2038
<pre>
</pre>

[BXMSPROD-2038] add QUARKUS_BOM_VERSION to Kogito and BAMOE Kogito properties generator jobs

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2021
<pre>
</pre>

[BXMSPROD-2021] add new OSL images in osl-trigger-umb-message job

---

job-dsls/jobs/prod/prod_rhbop_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_rhbop_trigger_umb_message.jenkinsfile

**JIRA**: [BXMSPROD-2058](https://issues.redhat.com/browse/BXMSPROD-2058)
* https://github.com/kiegroup/kie-ci/pull/1496 (applied the same change we did for OSL)
<pre>
</pre>

[BXMSPROD-2058] add param for Drools prod version in rhbop-trigger-umb-message job

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2021
Operator and bundle productized images will not be part of OSL 1.30
<pre>
</pre>

remove operator and bundle images from osl-trigger-umb-message job

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

bumped up for new version

---

.ci/actions/backporting/action.yml

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-2084
etc. 
<pre>
</pre>

[BXMSPROD-2084] migrate to kiegroup/git-backporting

---

.ci/actions/backporting/action.yml

**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-2087
- https://github.com/kiegroup/git-backporting/pull/72
- https://github.com/kiegroup/git-backporting/pull/73
<pre>
</pre>

[BXMSPROD-2087] how to trigger test on backported prs info

---

job-dsls/jobs/osbs/bamoe_kogito_images_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/bamoe_operators_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_kogito_images_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_operators_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy
job-dsls/src/main/resources/job-scripts/prod_bamoe_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_bamoe_kogito_create_images_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_create_release_trackers.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_create_images_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_move_jiras_qa.jenkinsfile

Refactored some jobs to use `util.runWithPythonVirtualEnv` utility function whenever a python env is needed. This new utility has been added in [this PR](https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/277).
**JIRA**:
https://issues.redhat.com/browse/BXMSPROD-2061
etc. 
<pre>
</pre>

[BXMSPROD-2061] using runWithPythonVirtualEnv when python env is needed

---

job-dsls/gradle.properties

upgrade of Jenkins version

---

job-dsls/src/main/resources/job-scripts/prod_create_release_trackers.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_move_jiras_qa.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2061
<pre>
</pre>

[BXMSPROD-2061] import missing jenkins-pipeline-shared-libraries to use methos from util.groovy

---

job-dsls/src/main/resources/job-scripts/prod_create_release_trackers.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_move_jiras_qa.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2061
<pre>
</pre>

[BXMSPROD-2061] util method should be invoked inside script block

---

job-dsls/jobs/kie/kie-tools/send_UMB_trigger_after_version_upgrade.groovy
job-dsls/jobs/kie/kogito/kie_tools_prerelease_branch_UMB_trigger.groovy

changed nodes to not execute on build-in

---

job-dsls/jobs/kie/branch/compile_downstream_build.groovy
job-dsls/jobs/kie/branch/compile_downstream_build_7_x.groovy
job-dsls/jobs/kie/branch/deploy_jobs.groovy
job-dsls/jobs/kie/branch/deploy_jobs_7_x.groovy
job-dsls/jobs/kie/branch/downstream_pr_jobs.groovy
job-dsls/jobs/kie/branch/downstream_pr_jobs_7_x.groovy
job-dsls/jobs/kie/branch/downstream_production.groovy
job-dsls/jobs/kie/branch/downstream_production_7_x.groovy
job-dsls/jobs/kie/branch/pr_jobs.groovy
job-dsls/jobs/kie/branch/pr_jobs_7_x.groovy

https://issues.redhat.com/browse/DROOLS-7533
Preparing `kie-jpmml-integration` main for Drools v8: https://github.com/kiegroup/kie-jpmml-integration/pull/76
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2360

DROOLS-7533 Move `kie-jpmml-integration` jobs to 7.x

---

job-dsls/gradle.properties

upgraded Jenkins version

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Upgrade next RHPAM product version to 7.13.5

---

job-dsls/jobs/osbs/bamoe_kogito_images_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_kogito_images_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy

Jenkins podman nodes has cekit 4.9.1 which is now required to trigger builds on OSBS
Jira: https://issues.redhat.com/browse/BXMSPROD-2122
<pre>
</pre>

[BXMSPROD-2122] use nodes with podman for OSBS builds

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

add operator and bundle images in osl-trigger-umb-message job

---

job-dsls/jobs/prod/prod_sync_branches.groovy
job-dsls/src/main/resources/job-scripts/prod_sync_branches.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2121
<pre>
</pre>

[BXMSPROD-2121]  allow target and source branches to have different names in sync-branches job

---

job-dsls/jobs/prod/prod_cron_meta_nightly_rhpam_pipeline.groovy

rename job name for prod_cron_meta_nightly_rhpam_pipeline.groovy

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

move back to daily OSL and drools-ansible nightlies

---

job-dsls/jobs/kie/branch/sonarcloud_daily.groovy

**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-2189
<pre>
</pre>

[BXMSPROD-2189] : Split maven run for test and sonar analysis - jdk11 and jdk17

---

job-dsls/jobs/kie/branch/compile_downstream_build.groovy
job-dsls/jobs/kie/branch/compile_downstream_build_7_x.groovy
job-dsls/jobs/kie/branch/downstream_pr_jobs.groovy
job-dsls/jobs/kie/branch/downstream_pr_jobs_7_x.groovy
job-dsls/jobs/kie/branch/downstream_production.groovy
job-dsls/jobs/kie/branch/downstream_production_7_x.groovy
job-dsls/jobs/kie/branch/pr_jobs.groovy
job-dsls/jobs/kie/branch/pr_jobs_7_x.groovy

Related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2496
- https://github.com/kiegroup/kie-ci/pull/1562
<pre>
</pre>

[BXMSPROD-2209] move downstream and PRs jobs to use rhel8

---

job-dsls/jobs/prod/prod_rhsa_errata_content.groovy
job-dsls/src/main/resources/job-scripts/prod_rhsa_errata_content.jenkinsfile

Related PRs:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/331
- https://github.com/kiegroup/kie-ci/pull/1563
<pre>
</pre>

allow to filter CVEs by a component name in rhsa-errata-content job

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

Jira : https://issues.redhat.com/browse/SRVLOGIC-383
<pre>
</pre>

[SRVLOGIC-383] add Management console image as part of OSL prod UMB message

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

add kn-workflow-cli-artifacts image as part of OSL prod UMB message

---

job-dsls/src/main/resources/job-scripts/prod_bamoe_staging.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_staging.jenkinsfile

do not use indy-admin when downloading artifacts in staging pnc artifacts jobs

---

job-dsls/jobs/seed_jobs/prod_seed_job.groovy

Jira: https://issues.redhat.com/browse/BXMSPROD-2214

[BXMSPROD-2214] update rhba.generate-status-page-data job via a-seed-job-prod

---

job-dsls/jobs/kie/branch/downstream_pr_jobs.groovy
job-dsls/jobs/kie/branch/downstream_production.groovy
job-dsls/jobs/kie/branch/prodProjects_downstream_production.groovy

move BAMOE v8 downstream and PRs jobs to use rhel8

---

.ci/actions/dsl-tests/action.yml

update upload-artifacts to v4 version

---

.ci/actions/surefire-report/action.yml

closes https://github.com/kiegroup/kie-ci/issues/1579
<pre>
</pre>

Update surefire-report plugin to latest v1

---

.ci/actions/maven/action.yml

update cache to v3 as v2 is not supported anymore

---

.ci/actions/maven/action.yml

updated actions to the latest versions
<pre>
</pre>

Updated used actions

---

.ci/actions/build-chain/action.yml
.ci/actions/dsl-tests/action.yml
.ci/actions/os-preparation/action.yml

trying to upgrade actions and set fixed BC version
<pre>
</pre>

upgraded actions for setup-java, BC and checkout -a
