kiegroup/kie-ci

job-dsls/jobs/downstream_pr_jobs.groovy

We need to be sure all the repos can be safely GWT compiled.
The kie-wb-distributions webapps have huge memory requirements.

gwt.compiler.localWorkers=1 for full downstream builds

---

job-dsls/jobs/downstream_pr_jobs.groovy

The correct order needs to be: 1) upstream repos builds, 2) PR repo
build and 3) the downstream build. However, since the upstream and
downstream builds are being manually configured, they ended up being
the first and second. So the PR repo build was executed _after_ the
downstream build, which makes no sense. Moreover the generated
WARs do not actually contain the changes from the PR, which is a big
issue. This is hopefully just a quick workaround before I find a better
way to fix it.

Workaround for the incorrect builders order

---

job-dsls/jobs/downstream_pr_jobs.groovy

We only need to archive the actual end-result WARs. The old
GLOB matches also e.g. kie-wb-webapp.war or kie-wb-common-showcase.war
which are not needed and only take up storage space.

Archive only the required WARs

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

The app (WAR) needs to be specified using the profile, otherwise
the tests are skipped. This is a recent configuration change, which
was forgotten to be reflected in the job configs.

Make sure the Selenium tests are executed for PR jobs

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

The downstream PR build will be executed automatically after the
standard build succeeds (green). It will still be possible to execute
just the downstream build. The tirgger phrases will now behave like this:
- "jenkins (re)test this" -> executes the standard build and if that one
succeeds, the downstream build will be triggered automatically
- "jenkins execute full downstream build" -> only the downstream build
gets triggered, no matter the state of the standard PR build
@mbiarnes could you please take a look? Should hopefully be working as expected.

Execute downstream PR build automatically

---

job-dsls/jobs/FlowJob.groovy
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_release_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

@mbiarnes please take a look
/CC @desmax74  - this should make sure the log files are always archived as a build artifacts.

Archive additional target/*.log files

---

job-dsls/jobs/FlowJob.groovy

@psiroky had to rename deploy-dir to deployDir as it appears that inside the DSL script you can't use twice the same name. deploy-dir=$WORKSPACE/deploy-dir gave me an cannot find deploy-dir - so I changed it to deployDir, and now the scripts work.

renamed directory for deploying locally

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

This reverts commit 710af7356d14435a3e4fca9d81a9b46e429f9f77.
The automatic triggering of downstream builds is overloading Jenkins.
Until a better solution is found the jobs will only be triggered by the
specific trigger phrase "Jenkins execute full downstream build"

Revert "Execute downstream PR build automatically"

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

This reverts commit 710af7356d14435a3e4fca9d81a9b46e429f9f77.
The automatic triggering of downstream builds is overloading Jenkins.
Until a better solution is found the jobs will only be triggered by the
specific trigger phrase "Jenkins execute full downstream build"

[7.3.x] Revert "Execute downstream PR build automatically"

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

This reverts commit 710af7356d14435a3e4fca9d81a9b46e429f9f77.
The automatic triggering of downstream builds is overloading Jenkins.
Until a better solution is found the jobs will only be triggered by the
specific trigger phrase "Jenkins execute full downstream build"

[7.2.x] Revert "Execute downstream PR build automatically"

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Keeping the builds for a long period of time causes the Jenkins
master to get swamped with data, which most likely will never be needed
again. Archiving the artifacts for seven days should be enough.

[7.3.x] Keep PR builds around only for 7 days (instead of 14)

---

job-dsls/jobs/FlowJob.groovy
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

kie-wb-distributions will soon contain third GWT webapp, which means
the build will start to fail with OOM. This is a quick fix which
will make sure only two parallel threads are used to build the
kie-wb-distributions repo.
CC @cristianonicolai

Use only two threads when building kie-wb-distributions

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

This should hopefully fix the occasional NPE seen with
maven-bundle-plugin. See https://www.mail-archive.com/users@felix.apache.org/msg17054.html
for more info.

Build 'deploy' and 'PR' jobs with Maven 3.5.0

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

This should hopefully fix the occasional NPE seen with
maven-bundle-plugin. See https://www.mail-archive.com/users@felix.apache.org/msg17054.html
for more info.

[7.3.x] Build 'deploy' and 'PR' jobs with Maven 3.5.0

---

job-dsls/jobs/deploy_jobs.groovy

It seems that using just the name is no longer supported. ID needs to be
specified. This is not ideal, but until we figure out a better way it
will have to do.

Use correct ID for provided settings.xml file

---

job-dsls/jobs/FlowJob.groovy

This is needed to save some disk space so that the builds would not fail
with "no space left on device".
This is the second part of the fix/workaround for the disk space issue. I've already tested this with custom job, so unless I made some mistake in the escaping, it should work as expected.

kie-all: run clean-up script after each repo build

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_release_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

@psiroky @mbiarnes The goal of this PR is to remove the Jenkins jobs for building/releasing the Dashbuilder repository master branch.
Please take a careful look. I did not fully understand the scripts and am almost certain I messed something up. In particular, I did not remove references to dashbuilder from [FlowJob](https://github.com/mbarkley/kie-jenkins-scripts/blob/move-dashbuilder-to-uf/job-dsls/jobs/FlowJob.groovy). It looks to me like a template you use for generating new job configurations. Is that correct?

Remove dashbuilder Jenkins jobs for master.

---

jenkins-slaves/ansible/kie-rhel7.yaml
job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_release_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

@psiroky @mbiarnes This is the PR that (I think) should fix the Jenkins jobs after the PR set including [this](https://github.com/kiegroup/appformer/pull/100) are merged.
I figured you could take a look ahead of time in case there are things I obviously did wrong. I intentionally did not rename every instance of uberfire->appformer, and versions are still currently the same. I will be sending another round of PRs in the future to align appformer versioning with the rest of KIE, at which point I will send PRs here to fix that as well.

Fix jobs to first step of uberfire->appformer migration.

---

job-dsls/jobs/FlowJob.groovy

upgraded forgotten new versions
Job kie-docker-ci-images-master failied today because versions couldn't been found. Looking for 7.6.0, but it was not there. This will be fixed with this PR.

fixed new versions

---

job-dsls/jobs/kie_release_jobs.groovy

changed the properties as kieVersion is required. Normally the kieVersion  is passed by a properties file but when running the jobs without this property file, alone,  kieVersion was missing as the input parameter was releaseVersion and the script requires kieVersion.

changed property names

---

jenkins-slaves/ansible/kie-rhel7.yaml

I saw reference to Uberfire repo and trying to build in CI job so removing here for ensuring it is gone https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/droolsjbpm-build-bootstrap-pullrequests/735/

removed uberfire git org/repo lines

---

job-dsls/jobs/downstream_pr_jobs.groovy

After discussion with @manstis we agreed that it would be very useful for QE if kie-wb.war, which is built in downstream PR jobs, would have sourcemaps included. That basically means that java source code would be added to the final war file, making client-side code debugging in the browser possible. 
Addition of sourcemaps was implemented in separate maven profile in [this PR](https://github.com/kiegroup/kie-wb-distributions/pull/678) and merged both on master and 7.5.x
The intention of this PR is to make sourcemaps appear in kie-wb war which is archived as a part of full downstream builds (and nowhere else). @mbiarnes can you please check if I added the profile to correct place and if yes, re-generate jenkins jobs after this is merged?

Enable sourcemaps profile in downstream PR jobs

---

job-dsls/jobs/kie_release_jobs.groovy
job-dsls/jobs/zanataPull.groovy
job-dsls/jobs/zanataPush.groovy

- a new DSL job is required for a temp. errai version (only for prod) like in daily builds
- the ZANATA version for Zanata projects changed to 7.7.0
- the jdk is defined as variable $javadk in DSJ jobs
IMPORTANT: please merge also https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/718

Prod errai

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

have to use double square bracket for variable definition and removed time outs in builds as they are to small depending the traffic on nodes

fixed parameter definition and removed timeout

---

job-dsls/jobs/pr_jobs.groovy

After my [PR which disabled execution of javadoc plugin](https://github.com/kiegroup/kie-jenkins-scripts/pull/237), drools-pullrequests jobs started to fail with
<details>
<summary>errors like this</summary>
<pre>
11:45:21 [INFO] ------------------------------------------------------------------------
11:45:21 [INFO] Reactor Summary:
11:45:21 [INFO] 
11:45:21 [INFO] Drools Multiproject ................................ SUCCESS [  4.082 s]
11:45:21 [INFO] KIE :: Test Utility Classes ........................ SUCCESS [ 22.561 s]
11:45:21 [INFO] Drools :: Core ..................................... SUCCESS [02:39 min]
11:45:21 [INFO] Drools :: Compiler ................................. SUCCESS [03:38 min]
11:45:21 [INFO] Drools :: Beliefs .................................. SUCCESS [ 24.705 s] …

Don't disable javadoc build in drools PR builder job

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Disabling javadoc won't be as easy because drools-distribution depens on javadoc artifacts as commented in the [previous PR](https://github.com/kiegroup/kie-jenkins-scripts/pull/241)
I'll have to find a better way to do it which doesn't cause build failures in drools. Until I do that, reverting the changes to fix drools build.

Revert changes disabling javadoc

---

job-dsls/jobs/downstream_pr_jobs.groovy

Part of an ensemble:
https://github.com/kiegroup/jbpm-wb/pull/1160
https://github.com/kiegroup/kie-wb-common/pull/1917
https://github.com/kiegroup/drools-wb/pull/877
https://github.com/kiegroup/appformer/pull/401
Also temporarily bumping timeout. This will be needed temporarily, because after disabling maven parallel build, the jobs are running slower now and timing out. Several speed improvements are coming soon, but until they're implemented, I need to increase it to prevent failures. @mbiarnes can you please check and merge?

AF-1248: Disable gwt compilation of showcases in downstream PR jobs

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/pr_jobs.groovy

Some context:
@yurloc is migrating some of our projects from using `org.codehaus.mojo:gwt-maven-plugin` to `net.ltgt.gwt.maven:gwt-maven-plugin`.
Some build steps within our jenkins automation are skipping (slow and unnecessary) gwt compilation by using `-Dgwt.compiler.skip=true`. However that property only skips compilation for the former plugin and has no effect on the latter.
To fix this I'm adding `-Dgwt.skipCompilation=true` (as described in the [docs of the plugin](https://tbroyer.github.io/gwt-maven-plugin/compile-mojo.html)) everywhere where the first property is already used. This is expected to speed-up some jobs by couple of minutes.
@mbiarnes @yurloc please check.

Also skip gwt compilation for the new tbroyer gwt-maven-plugin

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

disabled for not running every night - can be enabled again when we need it to execute

disabled pipeline job for 7.7.x

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

we need to adjust the timeout for the first run (about 8 hours) because it 7,11,x prod build doesn't run yet
with 90 minutes it is aborted

adjusted timeout value for the first run

---

jenkins-slaves/ansible/kie-rhel7.yaml
job-dsls/jobs/kie_release_jobs.groovy

@mbiarnes Selenium tests in PR jobs started to fail recently, because it takes too long to start firefox before tests. This is the first attempt at stabilization: I updated to latest available firefox ESR (Extended Support Release) versions. Also replaced one usage of (quite old) firefox 38 and replaced it with 45. 
As a followup to this PR I will update to latest version of selenium in the next sprint, so we can star using even more recent version of firefox (52 and 60) which currently used version of selenium doesn't yet support.

Update firefox to latest ESR versions

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kie_release_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Migrate selenium testing to the latest firefox. @mbiarnes please don't merge yet. This will require refactoring of selenium tests. I'll get back to this soon.
Part of an ensemble:
https://github.com/kiegroup/kie-jenkins-scripts/pull/335
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/840
https://github.com/kiegroup/kie-wb-distributions/pull/820

BAQE-96: run selenium tests with latest Firefox (60esr)

---

job-dsls/jobs/downstream_pr_jobs.groovy

When updating to latest selenium I made it mandatory to specify
Firefox binary path (to avoid using firefox provided by OS).
https://github.com/kiegroup/kie-wb-distributions/blob/master/kie-wb-tests/kie-wb-tests-gui/pom.xml#L21-L22
That lead to failures in full downstream builds, because that property wasn't specified.

Set webdriver.firefox.bin for downstream repos

---

job-dsls/jobs/deploy_jobs.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kie_release_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Cherry-picking Firefox version update for selenium tests from master to 7.11.x

Use latest version of Firefox in selenium tests

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

The proposed command has the following advantages:
- is lightning fast (we're not spawning multiple find and rm processes)
- is more thorough. `git clean -ffdx` will get you to the same state as fresh clone.
- is more future proof (by not having to enumerate explicitly what to delete, we don't have to think about what artifacts to delete)
- the implementation is much shorter

Improve cleanup script

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

My previous change broke the kieAllBuild, because the cleanup also removed the junit reports, that the post build step tries to archive, resulting in failure:
```
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```
This change tries to rectify this by adding the test reports to the index, preventing their removal in the `git clean` step.

Don't remove JUnit reports when cleaning up build artifacts

---

job-dsls/jobs/compile_downstream_build.groovy

(cherry picked from commit 3003755b8a543f7d2001b0864bff2d97c93d69e8)
for the compilation of all downstream reps skipping tests and skipping gwt compilation

[7.11.x] added new groovy script

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kie_release_jobs.groovy

I randomly noticed we're using EAP7.1.0 in integration tests.
Bumping to latest EAP 7.1.x version.
I checked that this update works by running tests in kie-wb-distributions that use this property
```bash
cd kie-wb-distribution/kie-wb-tests
mvn clean verify -Pkie-wb,eap7 -Deap7.download.url=http://download.eng.brq.redhat.com/released/JBoss-middleware/eap7.1.4/jboss-eap-7.1.4-full-build.zip
```
I also found two other test suites that use this property. @sutaakar could you please check if this EAP update won't break those integration tests an if this is ok to merge?
https://github.com/kiegroup/jbpm/blob/master/jbpm-container-test/pom.xml#L41
https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-tests/pom.xml#L73

Use the latest version of EAP in integration tests

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

master start an hour before 7.14.x - so they can't have any more the same prefix.
Tested this night!

new trigger time for daily build

---

job-dsls/jobs/downstream_pr_jobs.groovy

[TransformerServletTest](http://janhrcek.cz/random-failures/#/class/org.jbpm.designer.web.server.TransformerServletTest) has been failing since we switched to new upshift environment.
The test class fails to initialize because it can't connect to X11 window server.
<details>
<summary>see the exception</summary>
<pre>
java.awt.AWTError: Can't connect to X11 window server using ':72' as the value of the DISPLAY variable.
at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
at java.security.AccessController.doPrivileged(Native Method)
at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
at …

Enable 'Create a dedicated Xauthority file per build' in xvnc configuration

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

adds via DSL groovy script (configure block)  the trigger that is now configured manually directly in the dailyBuild- pipeline job since it wasn't recognized by normal DSL api.
Once this works it will be backported to 7.18.x.

added configure block for DSL unknown trigger

---

job-dsls/jobs/submarine.groovy

@mswiderski I cannot add a publisher to a  pipeline job (the PR #438) - sorry. It test "green" but finally it ididn't added the mail. So I hope now it works. The mail function was added to each submarine job.

edited mail publisher for submarine jobs

---

job-dsls/jobs/deploy_jobs.groovy

Follow-up of DROOLS-1781: replaces findbugs-maven-plugin

Fix spotbugs in the deploy job of droolsjbpm-build-boostrap

---

job-dsls/jobs/submarine.groovy

avoids that folders KIE/master/submarine are created inside KIE -

fixed path for submarine Jenkisn jobs

---

jenkins-slaves/README.adoc
jenkins-slaves/add-osbs.sh
jenkins-slaves/ansible/data/rhba-osbs/.gitignore
jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/rhba-osbs/.gitignore

This change adds dependencies and a script to the Jenkins image
which allows cekit osbs builds of rhba images. Since the items
necessary reference internal systems, the optional add-osbs.sh
script has been added to clone the necessary repository and install
the files. The rhba-osbs role and data directories have been stubbed
out for backward compatibility, and the README updated.
Signed-off-by: Trevor McKay <tmckay@redhat.com>

[BXMSPROD-161] Add cekit build capability to Jenkins image

---

job-dsls/jobs/slave_image_build.groovy

This change include the extra functionality needed on the
Jenkins slave to do osbs builds from cekit.

Add osbs build functionality to slave_image_build.groovy

---

job-dsls/jobs/sonarcloud_daily.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

The daily jobs for SonarCloud analysis. PR analysis cannot be done without full branch analysis, as SonarCloud might become out of sync with the repository after a couple of weeks.
Moreover, this will keep project's summary statistics up-to-date.
This initial work enables daily analysis for drools and optaplanner, other repositories will follow.

Sonarcloud daily jobs

---

job-dsls/jobs/pr_jobs.groovy

@mariofusco agreed with turning the PR analysis on for Drools. Daily analysis is covered by https://github.com/kiegroup/kie-jenkins-scripts/pull/459

DROOLS-3569 Enable SonarCloud PR analysis for Drools

---

job-dsls/jobs/seed_job.groovy

nitpicking: now are enabled all *.groovy scripts in this rep - also Zanatas, dailyBuilds and releases
(we had before extra seed jobs for this - but it is not needed)

enabled all *.groovy scripts

---

job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

PR and downstream PR jobs use kieAllBuild Maven settings which specify our local Nexus mirror to speed up builds and avoid downloading artifacts from Maven Central directly.

job-dsls: use Maven settings with Nexus mirror

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

(cherry picked from commit d6aa3bc3467dddcd22925e16b86153ecd9f7e1bc)
Since the structure of directories in Jenkins-jobs changed the docker job is not found any more. A new variable is needed.

added new variable for the full path to docker script

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

Reverts kiegroup/kie-jenkins-scripts#482
checked. Master wasn't changed and worked! 7.23.x didn't find the kie-ci-images job. This PR has to be reverted.
The ahead going failures were caused by another reason.

Revert "corrected path to automatically trigger jenkins job"

---

job-dsls/jobs/sonarcloud_daily.groovy

The property turn on additional test coverage that should appear in SonarCloud statistics.

Include drools turtle tests into the sonar analysis

---

jenkins-slaves/packer-kie-rhel7.json

Using this type of OpenStack flavor will create the instance in a special OpenStack aggregate with nested virtualization disabled, thus avoiding the situation causing SIGSEGV errors.

Use no.nested.virt flavor to avoid sigsegv problem

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

these PR makes only sense to merge once https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/984 was merged as it contains the modifications for the update-version-all.sh script used in kie_dailyBuild_pipeline.groovy
- all "manual" (via sed) version updates were removed since now they are done in the update script
- errai parameter were removed (and any parameter that links to it), as it is not any more needed to handle it like a daily build version - we have it right now as *.Final version

Fix daily build

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

In a previous commit the appformer version for the prod build were removed. This was re-added.

re-added accidently removed appformer version for prod builds

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

... the correct uberfire version was missing [uberfireVersion + date]
The dailyBuild worked with uberfireVersion instead uberfireVersion+date
i.e. 2.21.0 instead of 2.21.0.20190719

added date suffix to uberfire

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy

with reference to eap7, which does not any more exist in upstream, the test fails

removed dependencies to eap7 in community

---

jenkins-slaves/ansible/data/config/vnc/xstartup

@mbiarnes @winklerm this should setup the slaves with additional files. There already is a `passwd` file, so I am not sure how to proceed.
```
sh "wget -P $HOME/.vnc <url>/.vnc/passwd"
sh "wget -P $HOME/.vnc <url>/.vnc/xstartup"
sh "chmod 600 $HOME/.vnc/passwd"
```

AF-2004: Fix vscode tests not running on jenkins slaves

---

job-dsls/jobs/springboot_pr_job.groovy

It seems I was too optimistic. 90 minutes is not enough.

Increase defailt timeout for Spring Boot PR check

---

job-dsls/jobs/kie_dailyBuild_pipeline.groovy
job-dsls/jobs/kogito.groovy

We need to react only on messages we sent and not rely on topic only, since there might be topics with wildcards.

jobDSL: introduce UMB selector to react only on our messages

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

ZANATA_VERSION could not be upgraded yet, because the Zanata server is not up and running. There are right now a lot of movements related to this. Master is still connected to Zanata 7.27.0 version.

updated new costants

---

job-dsls/jobs/pr_jobs.groovy

120 minutes are not enough to run all Kie server integration tests
@rsynek @mbiarnes Can you please check?

Raise default timeout for droolsjbpm-integration PR check to 180 minutes

---

job-dsls/jobs/pr_jobs.groovy

120 minutes are not enough to run all Kie server integration tests
Cherrypick of https://github.com/kiegroup/kie-jenkins-scripts/pull/557

[7.26.x] Raise default timeout for droolsjbpm-integration PR check to 180 minutes

---

job-dsls/jobs/DailyBuild_pipeline.groovy
job-dsls/jobs/DailyBuild_prod_pipeline.groovy

Adds a post action that only executes if the result of pipeline  was FAILURE.
Before, when the pipeline failed in the deploy step - the stage of sending an email was not executed since it failed before this step.
User only get an email notification when the pipeline result was SUCCESSFUL or UNSTABLE.
With this post action the user gets an email notification also when the pipelines result is FAILURE (i.e when the build&deploy fails)

added email function if the pipelines result was FAILURE

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

The library is required to run Cypress UI tests in a headless mode.

PLANNER-1555 Install Xvfb to run Cypress tests

---

job-dsls/jobs/seed_job.groovy

it is better to list jobs individual in this seed job since all here listed jobs will be created in KIE/.
Some jobs (not here listed) have to be created in another directories (i.e. Tools).
With this PR we will prevent to have jobs created twice - in different folders.

individual listing of groovy jobs

---

jenkins-slaves/ansible/roles/common/tasks/main.yml

UI tests will be run from a docker container to isolate their dependencies from testing environment.
@mbiarnes this negates the previous commit as in the end I chose a different solution.

Remove unnecessary Xvfb dependency

---

job-dsls/jobs/springboot_pr_job.groovy

@mareknovotny @mbiarnes 
We didn't use provided settings.xml for the Springboot PR job build, just for upstream repositories. Because of that, the javascript tests were not compiled properly.

springboot-pr-job: Use provided settings.xml

---

job-dsls/jobs/communityRelease_pipeline.groovy

in case the pipeline was aborted and a new build required (i.e. after several days of sanity checks) a new mail will be send out, but this time not again the sanity test one.

2nd mail if a re-build were done after sanity checks

---

job-dsls/jobs/communityRelease_pipeline.groovy
job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/prodTag_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

- a new parameter LOCAL_MVN_REP (path to local maven directory) was added to constants
- a step of removing part of the .m2/repository/org was added to all build or deploy scripts
- a new hidden parameter had to be created m2Dir
- some steps in prodTag_pipeline.groovy were renamed as well as superfluous parameters removed

Install v sdeploy

---

job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy

changing email adresses etc. did that filters in gmail didn't work any more as expected. With this changes create new filters is easy and work again:
i.e.
from: jenkins@rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com
to: kie-jenkins-builds@redhat.com
subject: "master:daily-build"
or subject: "master:prod-daily-build"
or subject: "7.30.x:daily-build"
or subject: "7.30.x:prod-daily-build"

change wording in bodies of mail for better gmail filtering

---

job-dsls/jobs/prodTag_pipeline.groovy

added post build action:
in case the build breaks the stages where a mail is send (in this pipeline) are not reached.
This should never happen but in case a mail is send to bxms-prod@redhat.com.

added post script that sends mail only in case of failure

---

jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/rhba/tasks/main.yml

BXMSPROD-583
depends on https://github.com/kiegroup/kie-jenkins-scripts/pull/675
pom-manipulation-ext to pom-manipulation-cli
version upgraded to 3.8.1

BXMSPROD-583 pom-manipulation-ext to pom-manipulation-cli

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

@mareknovotny I see you don't like the manual change of constants. But the master daily build uses this constant for creating a new version: <constant><date>-suffix (i.e **7.32.0**.20200120-050152) -
when having the artifacts on QA Nexus it is nicer to have a name like this.
If you think it is better to have this resolved programmatically (sed job) let me know.

upgraded constant for master prefix

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

Cloning repository directly into workspace results in other repositories,
that are cloned in the job, to appear in a subdirectory of the main
repository.
Local tests via `gradlew test` passed.

Checkout github repository into a separate directory

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/downstream_pr_jobs.groovy
job-dsls/jobs/pr_jobs.groovy

This reverts commit 8bca9ed11ece488780c90c78c36eef76adba77f5.
@rsynek this had to be reverted since the PRs didn't find a pom - more complicated we thought

Revert "Checkout github repository into a separate directory (#695)"

---

job-dsls/jobs/seed_job.groovy

kogito-deploy will now executed by this job https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/kogito-deploy/ - so it is not any more needed as own job in own directory.
The existing https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/kogito-deploy/job/kogito-pipeline-master/ has been disabled

removed kogito job from seed job

---

job-dsls/jobs/communityRelease_pipeline.groovy

When the community release is re-triggered, but without the nee of a re-build - then it is not needed to execute the additional tests again.

Additional tests won't be executed if a re-build is not needed

---

job-dsls/jobs/communityRelease_pipeline.groovy

It is important that mail is sent after tags are pushed. It could be that upload scripts to filemgmt.jboss.org failes because of server issues - but then, although the BUILD was successful and the tags were pushed the pipeline job "fails" and no mails is send. So the send mail stage was moved from the last position to the stage after the push tags stage.

change order of stages

---

job-dsls/README.MD
job-dsls/jobs/downstream_pr_jobs.groovy

Full downstream build needs to use gui-testing label for running kie-wb-common as this repository contains selenium tests.

KOGITO-1458: Start kie-wb-common with gui-testing label in FDB

---

job-dsls/jobs/communityRelease_pipeline.groovy

@mareknovotny I saw in the last execution of community release that an email is not send if the build fails. I added this stage here.

added stage for sending an email in case the deploy fails

---

job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy

- mail not send if the build result was successful (only if the previous build was different)
- build log is created via a script and attached to mails
- cleanWs() and junitTests were moved to POST_BUILDS actions

extEmail as POST_BUILD action with attached build log for daily builds

---

job-dsls/jobs/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/pr_jobs.groovy

This should attach a compressed consoleText (last 1000 lines) as error.log.gz to each failed or unstable PR.
Mails are send when build status is FAILED or UNSTABLE, also for each build that is successful but in the previous run was different (FIXED). A mail is not send when the build was successful (when previous run also was successful)
This was tested for lienzo-tests PR in case of SUCCESS, UNSTABLE, FAILED, FIXED
All situations respond with the expected behaviour.

attached compressed build log to POST_BUILD extMail function

---

job-dsls/jobs/communityRelease_pipeline.groovy
job-dsls/jobs/dailyBuild_pipeline.groovy

@jomarko and me noticed that we still use 7.2 in our daily pipelines.
related PR kiegroup/droolsjbpm-integration#2088

JBPM-9044 - Upgrade kiegroup repos to Wildfly 18.0.1.Final

---

job-dsls/jobs/communityRelease_pipeline.groovy
job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/prodTag_pipeline.groovy
job-dsls/jobs/seed_job.groovy

with the removal of pr_jobs.groovy and the upgrade of Maven version we are sure tha the jobs are not overridden again and the "old" Maven 3.5.2 version applied.
As FDBs, downstream.production and upstream builds are using [Jenkinsfile](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/Jenkinsfile#L16) they use Maven 3.5.4 (IIRC this was a buggy version of Maven). Not clear to me where this [constant](https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy#L21) is used. So I left it like it is. To have in mind that we are using somehow right now three different maven version.
I would syncr. all Mavens to 3.6.3.

Tiny fixes

---

job-dsls/jobs/compile_downstream_build.groovy
job-dsls/jobs/pr_jobs.groovy

@mareknovotny removal of parallel builds -T1C
the normal a_seed_job in Jenkins/KIE/master was disabled and a new one created a_seed_job_ONLY_PRs (this is not triggered automatically, has to be started manually after merging this PR)
When all pr_jobs and compile_downstream_builds are created again and after verifying everything is OK and we don't use any more -T1C the job a_seed_job_ONLY_PRs can be removed and the job a_seed_job has to be enabled again.

removal of parallel builds

---

job-dsls/jobs/communityRelease_pipeline.groovy

if not origin-repository it takes some hours/days until the link works.
Right now when people receive this automatic mail the links are empty:
404 - Path /org/kie/business-central/7.40.0.Final/ not found in group repository "Public JBoss Repository Group" [id=public-jboss].
This will change when using origin-repository

changed URL to deployed artifacts in mail

---

jenkins-slaves/ansible/kie-rhel7.yml
jenkins-slaves/ansible/roles/common/tasks/main.yml

We need to include the needed CAs into the kie-rhel* image in order to be able to use https to specific servers.

Include RH CAs into kie-rhel* image

---

job-dsls/jobs/prodTag_pipeline.groovy

the **/** broke the link in the mail sent

removed slash that breaks link

---

job-dsls/jobs/deploy_jobs.groovy

these changes create all deploy jobs ho we want.
- drools triggers optaplanner-7.x
- optaplanner-7.x has as upstream branch master and current 7.x
- the triggered jobs of optaplanner-7.x are fine

BXMSPROD-888: updated deploy job for optaplanner to use right branch

---

job-dsls/jobs/seed_job.groovy

disabled new jobs in the seed job - so no overwrite

removed new PR jobs

---

job-dsls/jobs/communityRelease_pipeline.groovy

@Ginxo additional test of community pipeline doesn't work because it says: 
`rmdir: failed to remove ‘kie-wb-distributions-<version>’: Directory not empty`
**rm -rf** removes all.

changed rmdir by rm -rf in additional test

---

jenkins-slaves/ansible/roles/smee/tasks/main.yml

https://issues.redhat.com/browse/BXMSPROD-983
According to `npm` ansible documentation, `version` is the one to be used

BXMSPROD-983 smee-client forced to be 1.1.0

---

job-dsls/jobs/pr_jobs.groovy

[JBPM-9406](https://issues.redhat.com/browse/JBPM-9406)
The PR check has a timeout of 40 minutes and it makes it in time very rarely. We should increase the timeout to 60 minutes.
<pre>
</pre>

JBPM-9406 - jbpm-work-items PR check times out because of a low timeout

---

job-dsls/jobs/pr_jobs.groovy

I am removing the trigger for the master branch of Optaweb repositories as I've provided similar PR pipelines for these as for the OptaPlanner repo.
**JIRA**: https://issues.redhat.com/browse/PLANNER-2202
<pre>
</pre>

PLANNER-2202 Create PR pipelines for Optawebs

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

The prefix of our artifacts we create in daily builds should be **7.48.0** since master branch was updated to 7.48.0-SNAPSHOT
The nightly version has **7.47.0.20201130-051112**. It still uses the prefix **7.47.0** - this have to be changed.

upgraded master to 7.48.0 prefix

---

job-dsls/jobs/pr_droolsjbpm_tools.groovy
job-dsls/jobs/seed_job.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/PrDroolsjbpmToolsJob.groovy

[BXMSPROD-1124](https://issues.redhat.com/browse/BXMSPROD-1124)
Since droolsjbpm-tools forms not any more part of the repositories used in community kiegroup, it has not any more upstream or downstream build assigned. Thus it has to be created otherwise then the common PRs.

BXMSPROD-1124: added pull request for droolsjbpm-tools

---

jenkins-slaves/packer-kie-rhel-jenkins-agent.json

Use a different OpenStack provider network (the same as Jenkins uses for creating agents) to avoid network unreachable issues.
<pre>
</pre>

images: use provider_net_cci_8 for image template machine

---

job-dsls/jobs/deploy_jobs.groovy

All of the opta repo's use release=8, but "release" is only available in JDK 11+ (not in JDK 8). So they need to be build with JDK 11, even though their output are JDK 8 compatible.

Use JDK 11 for optawebs and optaplanner-quickstarts

---

job-dsls/jobs/automatic_web_publishing.groovy
job-dsls/jobs/communityRelease_pipeline.groovy
job-dsls/jobs/dailyBuild_jdk11_pipeline.groovy
job-dsls/jobs/dailyBuild_pipeline.groovy
job-dsls/jobs/dailyBuild_prod_pipeline.groovy
job-dsls/jobs/deploy_development_version.groovy
job-dsls/jobs/errai_pr.groovy
job-dsls/jobs/kieAll_meta_pipeline.groovy
job-dsls/jobs/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/kie_tools_seed_job.groovy
job-dsls/jobs/kogito_docs_upload.groovy
job-dsls/jobs/prodTag_pipeline.groovy
job-dsls/jobs/reduced_drools_release.groovy

- changes daily-build-master-docker-images in dailyBuilds master from free style job to pipeline job
- hard coded values in pipelines were replaced by variables 
ToDo: once the new nodes with Rhel7 and all requested docker configuration are created 
the label def AGENT_DOCKER_LABEL= "kieci-02-docker" should be replaced by the recent machine. 
Same for def artifactsPath="/home/docker/kie-artifacts/$kieVersion" - since the path will be /home/jenkins./..
<pre>
</pre>

New daily docker

---

job-dsls/jobs/kieAll_meta_pipeline.groovy

https://github.com/kiegroup/kie-jenkins-scripts/pull/904
<pre>
</pre>
IMPORTANT: there was a bug - instead of `7.48.x-jdk11-pipeline` `master-jdk11-pipeline` was used.
In any case, right now this line was removed and not fixed as we don't want a JBK 11 for 7.48.x.

removed the daily build pipeline for JDK 11 and 7.48.x branch

---

job-dsls/jobs/sonarcloud_daily.groovy

I noticed I was still receiving warnings about SonarCloud dropping Java 8, recommending upgrading the Java version in some of the KIE group repositories. These jobs are apparently the source of the warnings - they run analysis of the long-lived branches.
It you have any idea how to replace these jobs by a more elegant solution, I am happy to discuss it.

Run SonarCloud daily on Java 11

---

job-dsls/jobs/communityRelease_pipeline.groovy

[BXMSPROD-1162](https://issues.redhat.com/browse/BXMSPROD-1162)
Since the step that uploads the binaries to Nexus fails in 70% of all executions because of network failures (when it is to slow the upload takes to long and we get an 401 error) the community pipeline fails and the last steps have to be done manually.
We use now the same approach as on daily builds - zip a file, upload the zipped file that is de-compressed automatically on Nexus.
This was tested bu a fake release and the step succeeded.
<pre>
</pre>

Community binaries upload

---

job-dsls/jobs/sonarcloud_daily.groovy

The master branch analysis was not working since November due to an incorrect projectKey. The PR fixes it, to connect to https://sonarcloud.io/dashboard?id=org.optaplanner%3Aoptaplanner.
<pre>
</pre>

Override sonar.projectKey for OptaPlanner

---

job-dsls/jobs/dailyBuild_jdk11_pipeline.groovy

The docker images constructed with `jdk11` will have absolute the same name as the ones  constructed with `jdk1.8`. Both use the very same dockerfile. Right now the problem is the script [docker-clean](https://github.com/kiegroup/kie-docker-ci-images/blob/master/scripts/docker-clean.sh) .
Supposing the `jdk1.8` pipeline executes before the `jdk11` pipeline and the docker images built with `jdk11` would fail because of any reason - the `docker-clean` script will have been executed before the image build and so all images with a certain name would have been erased - these names would be the very same for `jdk1.8` and `jdk11`. 
The before built `jdk1.8` images would be removed and finally there would be none docker image of master branch.
Maybe …

Docker jdk11

---

job-dsls/jobs/communityRelease_pipeline.groovy

Added a step that sends automatically a mail to bsig and the leads when the release pipeline is started.
Once the release branches are created this will not sent any more.  
<pre>
</pre>

added step for automatic email sending when the build starts

---

jenkins-slaves/ansible/data/service/smee-client-build.sh
jenkins-slaves/ansible/data/service/smee.service.sh.j2
jenkins-slaves/ansible/roles/smee/tasks/main.yml

Add workaround for [1] by building smee-client from a fork with the fix [2].
[1] https://github.com/probot/smee-client/issues/156
[2] https://github.com/probot/smee-client/pull/162
<pre>
</pre>

images: add workaround for smee-client issue 156

---

jenkins-slaves/ansible/kie-rhel.yml

**JIRA**: 
[KOGITO-4767](https://issues.redhat.com/browse/KOGITO-4767)
* https://github.com/kiegroup/kogito-runtimes/pull/1168

KOGITO-4767 - Upgrade GraalVM to version 20.3.1.2

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

- replaces the `original-repositories.jboss.org/` URL by `repositories.jboss.org/`
The problem was, that somehow the `repositories.jboss.org` only get updated if there was before a request for certain artifacs.
i.e.: when the artifacts are uploaded to a staging repository for sanity checks these are not visible in `repositories.jboss.org` until there is a request for an artifact. Before i.e. https://repository.jboss.org/nexus/content/groups/kie-group/org/kie/business-central/7.52.0.Final is loaded and accessible the has to be before a request for i.e. https://repository.jboss.org/nexus/content/groups/kie-group/org/kie/business-central/7.52.0.Final/business-central-7.52.0.Final-wildfly-deployable.zip.
Once an artifact is requested the …

replaced origin-repositories.jboss.org

---

job-dsls/jobs/kie/master/sonarcloud_daily.groovy

The job has been replaced by GHA: https://github.com/kiegroup/optaplanner/blob/master/.github/workflows/sonarcloud.yml

Remove OptaPlanner SonarCloud daily job

---

job-dsls/build.gradle
job-dsls/gradle.properties

this change was done to match Jenkins and DSL version on `eng-jenkins`.
There are some DSL definitions that changed (i.e triggers in pipeline). These changes are needed.
Problem: I can imagine that these PRs won't run on RHBA Jenkins, since there is an older JENKINS version.
Suggestion: merge this PR after migration to `eng-jenkins`
<pre>
</pre>

upgraded DSL version

---

job-dsls/jobs/prod/prod_offline_repo_builder.groovy
job-dsls/src/main/resources/job-scripts/prod_offline_repo_builder.sh

Use a release repository group instead of replacing MRRC to include all necessary repositories

Use a release repository group

---

jenkins-slaves/ansible/roles/kie/tasks/main.yml
jenkins-slaves/packer-kie-rhel-jenkins-agent.json
jenkins-slaves/packer-kie-rhel7-vars.json

Fix getting HTTP 403 Forbidden when attempting to download Groovy and avoid using an obsolete flavour.
<pre>
</pre>

images: fix Groovy download URL

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy

kogito-tooling fdb for creating V7 artifacts (for sanity checks) is not needed any more
<pre>
</pre>

removed step for kogito-tooling fdb

---

job-dsls/jobs/kie/master/downstream_pr_jobs.groovy

Increased timeout for FDB on droolsjbpm-build-boostrap to 840 mins (14 hours)
<pre>
</pre>

[7.52.x] Increasing FDB time out for droolsjbpm-build-bootstrap jobs

---

job-dsls/jobs/kie/master/downstream_pr_jobs.groovy

Timeout for droolsjbpm-build-bootstrap increased to 840 mins (14 hours)
<pre>
</pre>

Increasing FDB time out for droolsjbpm-build-bootstrap jobs

---

job-dsls/jobs/kie/master/i18n_translations.groovy

@mareknovotny this groovy scripts adds a job for downloading the file with i18n translations 
This [PR](https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/57) should also be merged to have the managed file always available.
<pre>
</pre>

added groovy script for getting the i18m translations

---

job-dsls/jobs/kie/master/compile_downstream_build.groovy
job-dsls/jobs/kie/master/downstream_pr_jobs.groovy
job-dsls/jobs/kie/master/downstream_production.groovy
job-dsls/jobs/kie/master/jenkins_shared_libs.groovy
job-dsls/jobs/kie/master/pr_jobs.groovy
job-dsls/jobs/kie/master/pr_jobs_7_x.groovy
job-dsls/jobs/kie/master/prodProjects_downstream_production.groovy
job-dsls/jobs/kie/master/upstream.groovy

the cancelOnUpdate is now enabled on all PR jobs on the `eng-jenkins`
<pre>
</pre>

added cancelBuildOnUpdate

---

job-dsls/jobs/kie/master/automatic_web_publishing.groovy

The exclusion of optaplanner-website prevents that the seed-jobs execution overrides the disabled job again and enables it.
There is a new job for the [optaplanner-website publishing](https://eng-jenkins-csb-business-automation.apps.ocp4.prod.psi.redhat.com/job/KIE/job/master/job/webs/job/optaplanner_web_publishing_bake/)
<pre>
</pre>

excluded optaplanner-website from automatic publishing with Rake

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy

this assures that kie-ci user can push to GitHub from kie-releases machine
[since we changed the kie-relaeses machine the keys stored on this machine are not any more available. For this reason the last community release was twisted since pushes couldn't be done] 
<pre>
</pre>

added user metadata step to assure user can push to github

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy

step of user metadata had to be changed in it's order to work with all reps, not only with droolsjbpm-build-bootstrap.
<pre>
</pre>

changed order in step for user metadata

---

job-dsls/jobs/kie/master/communityRelease_pipeline.groovy

If a build fails there are now files archived.
Increased the number of builds to save - 3 is definitively to small.
<pre>
</pre>

added more builds to store in logRotator

---

jenkins-slaves/ansible/kie-rhel.yml

The build chain tool is not properly taken into account for excluded projects. kiegroup/github-action-build-chain#160 solves the problem
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1413
**related PR**
- https://github.com/kiegroup/github-action-build-chain/pull/160
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/527
- https://github.com/kiegroup/optaweb-employee-rostering/pull/654
- https://github.com/kiegroup/optaplanner/pull/1418
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/528
- https://github.com/kiegroup/optaweb-employee-rostering/pull/655
<pre>
</pre>

BXMSPROD-1413 build-chain upgraded to 2.3.5

---

job-dsls/jobs/kie/main/downstream_pr_jobs.groovy
job-dsls/jobs/kie/main/pr_jobs.groovy

The `main` branch was added as hard coded parameter. Now, after the renaming we want to prevent to have in the config twice the same branch.  The hard coded branch could be removed.
<pre>
</pre>

removed hard coded main branch

---

job-dsls/jobs/prod/prod_pr_jobs.groovy
job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1259
After too much time and many considerations I decided to go back to basics and approach the task with this change. The primary objective with the change is to keep it self contained in a single repository and make it easy to follow and understand what the pipeline is really doing. Once a job is created is pretty simple to understand what's happening by just inspecting the pipeline steps. Jenkins shared libraries have to be planned really carefully as they get cluttered pretty easily.
Note: this changes relies on the nightly build and since the rename to `main` branch it hasn't been produced a new nightly so there's not available …

BXMSPROD-1259

---

job-dsls/jobs/kie/main/communityRelease_pipeline.groovy

The community pipeline calls a new script to sync the proxies [1 and 2] with https://repositories.jboss.org since we were asked not to use any more https://origin-repositories.jboss.org.
[BXMSPROD-1434](https://issues.redhat.com/browse/BXMSPROD-1434)
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1058
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1722
<pre>
</pre>

BXMSPROD-1434: adapted changes in community_pipeline

---

job-dsls/jobs/prod/prod_pr_jobs.groovy

When a variable is defined in the PROD PR check jobs template but it's not provided in the configs for the job, it is replaced by a `null` string literal. This is to replace them with an empty string instead.

Replace undefined variables in PROD PR checks template with an empty string

---

job-dsls/jobs/kie/main/deploy_jobs.groovy

optaplanner main deploy job still exists [online.](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/deployedRep/) Since optaplanner main PRs will use build chain tool a deploy job is not any more needed. In the [deploy folder ](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/deployedRep/) there are optaplanner-7.x and  optaweb*-7.x deploy jobs
<pre>
</pre>

PIM deploy-job build now with jdk11

---

job-dsls/jobs/tools/tools_agent_image_build.groovy
job-dsls/jobs/tools/tools_agent_image_build_PR_test.groovy

Fix the name of bxms-jenkins repo branch used in image creation jobs.
<pre>
</pre>

Fix bxms-jenkins repo branch name for image creation jobs

---

job-dsls/jobs/kie/main/pr_jobs.groovy
job-dsls/jobs/kie/main/pr_jobs_7_x.groovy

**JIRA**: [BXMSPROD-1447](https://issues.redhat.com/browse/BXMSPROD-1447)
@mareknovotny regex is working a kind of strange in Jenkins - with this change a PR build is not any more triggered when a link is edited into comments 
<pre>
</pre>

BXMSPROD-1447: links will not trigger any more a build

---

job-dsls/jobs/kie/main/pr_jobs.groovy

**JIRA**: [BXMSPROD-1447](https://issues.redhat.com/browse/BXMSPROD-1447)
@mareknovotny regex is working a kind of strange in Jenkins - with this change a PR build is not any more triggered when a link is edited into comments 
etc. 
<pre>
</pre>

[7.59.x] BXMSPROD-1447: links will not trigger any more a build

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

caused by: https://github.com/kiegroup/kie-jenkins-scripts/pull/1122
Fixing `ERROR: No item named kogito.nightly/1.11.0 found` from https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/PROD/job/cron-meta-nightly-pipeline/165
<pre>
</pre>

[prod_cron_meta_nightly_pipeline] trigger kogito.nightly/1.11.0 ERROR

---

job-dsls/jobs/tools/tools_agent_image_sync.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Configured image sync matrix job to use the short workspace (without matrix axes values in directory names) as this practice is safer.
<pre>
</pre>

jobs: image sync matrix job uses short workspace

---

job-dsls/jobs/tools/tools_agent_image_build.groovy
job-dsls/jobs/tools/tools_agent_image_build_PR_test.groovy
job-dsls/jobs/tools/tools_agent_image_promote.groovy
job-dsls/src/main/resources/job-scripts/promoteImage.sh

Added jobs for promoting built and tested images to production by renaming it according to the following suffixes:
- the production image has `-latest` suffix, 
- the new candidate image has `-latest-new` suffix, 
- the backup of the original production image has `-fallback` suffix.
<pre>
</pre>

jobs: add image promotion script

---

job-dsls/jobs/kie/main/reduced_drools_release.groovy

Fixing the repository list to not rely on managed file in Jenkins casc.yml
@mbiarnes i changed directly the pipeline code in the job to test it rapidly, but this PR covers the all changes i did and which are on the existing job. So please review and merge to not loose the job again with running any seed job run.
<pre>
</pre>

Reduced Drools release pipeline: create repository-list in pipeline instead of relying on managed file

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/jobs/prod/prod_kogito_properties_generator.groovy
job-dsls/jobs/prod/prod_rhdm_properties_generator.groovy
job-dsls/jobs/prod/prod_rhpam_properties_generator.groovy
job-dsls/jobs/prod/prod_send_umb_message.groovy
job-dsls/jobs/prod/properties_generator.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

I propose to use a more appropriated label for nightly related jobs in order to speed up nightly jobs. Once the nightly build itself is over the rest of the pipeline is about to trigger the rest of the jobs (send UMB message, generate properties and so on) it takes around 40 minutes and most of that time is about to wait for an available slave instance. What if we open the label filtering to have more possibilities to get a free instance?
`prod_send_umb_message.groovy` job was missing -> created
Needed PRs:
- https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/135
<pre>
</pre>

nightly related jobs to priority

---

job-dsls/jobs/kie/kie-tools/upgradeVersions/deploy_SNAPSHOT_version.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/kie_meta_upgrade_pipeline.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/upgradeAll_kiegroup.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_kie_benchmarks.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_kie_cloud_tests.groovy
job-dsls/jobs/kie/kie-tools/upgradeVersions/upgrade_kie_prefix.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy

@mareknovotny these scripts are for automating the bump up of versions in all kiegroup community repositories & kie-benchmarks & kie-cloud-tests needed when a community release was done and all these versions have to be bumped up. Until now this was done manually. 
added script for upgrade version of kie-benchmarks
added script for upgrade version of kie-cloud-tests
added script for triggering all upgrade jobs
changed location and name of deploy_development_version
added upgrade jobs to  kie-tools seed-job
typo fixes
[BXMSPROD-1535](https://issues.redhat.com/browse/BXMSPROD-1535)
* referenced …

added scripts for upgrade version of community kiegroup repositories

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/jobs/prod/prod_multibranch_nightly.groovy

Now the rhos machine is stable we should probably remove the old one and rename the rhos01 to rhba.nightly, wdyt?
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1190
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1863
<pre>
</pre>

rhos01 nightly job renamed to rhba.nightly

---

job-dsls/jobs/kie/main/jbpm_web_publishing.groovy

renamed groovy script
The previous automatic-web-publishing job works only fro the jbpm-website.
Now there are two groovy jobs for the creation of automatic publishing jobs until the jbpm-website is migrated to jbake (like others: drools, optaplanner and kiegroup website).
<pre>
</pre>

renamed job to coincide with other website publishing jobs

---

job-dsls/jobs/seed_jobs/kogito_tools_seed_job.groovy

[BXMSPROD-1655](https://issues.redhat.com/browse/BXMSPROD-1655)
This is a part of this JIRA. The seed job has to be disabled for not overwriting the job we have renamed.
Now the DSL for the new job  
https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/kie-tools/job/kie-tools-prerelease-branch-UMB-trigger/
has to be done and then the seed job should be enabled again.
<pre>
</pre>

disabled temporally seed job

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy

Added the missing RHBA_RELEASE_VERSION parameter to Kogito prod nightly build meta pipeline.
<pre>
</pre>

prod nightly: set missing RHBA_RELEASE_VERSION parameter

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmContainerTestMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmTestCoverageMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieServerMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieWbTestMatrix.groovy

the information for main branch will be visible at https://kiegroup.github.io/droolsjbpm-build-bootstrap/job/daily-builds. The meil sending is redundant,. Most people don't read them.  
etc. 
<pre>
</pre>

removed sending mails from tests

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

Fixes the UMB topic handling of `-blue` streams, unified the approach with Nexus suffix.
<pre>
</pre>

prod_cron_meta_nightly_pipeline: handle both Nexus suffix and UMB topic

---

job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

`-jf` is for job filtering, it accepts regex
<pre>
</pre>

generate status page data. main and 7.59.x disabled for RHBA and kogito, 1.11.x for kogito

---

job-dsls/jobs/kie/main/deploy_jobs.groovy
job-dsls/jobs/kie/main/deploy_jobs_7_x.groovy

The subject of deploy jobs appear in zulip chats without the branch name. So it is impossible to see which deploy job is related to which branch.
Now it will appear **[$branch] kiegroup/$rep deploy $STATUS**
etc. 
<pre>
</pre>

added branch name to mail subject

---

job-dsls/jobs/kie/main/deploy_jobs.groovy

- added missing deploy jobs
- The subject of deploy jobs appear in zulip chats without the branch name. So it is impossible to see which deploy job is related to which branch.
Now it will appear **[$branch] kiegroup/$rep deploy $STATUS**
etc. 
<pre>
</pre>

added missing repos for deploy jobs

---

job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile

rhba-prod-nightly-metainformation nexus is composed only by nighty repositories
**JIRA**:  https://issues.redhat.com/browse/BXMSPROD-1796
<pre>
</pre>

[BXMSPROD-1796] update nexus nightly repository url

---

job-dsls/jobs/kie/main/errai_deploy.groovy
job-dsls/jobs/kie/main/errai_jdk8_pr.groovy
job-dsls/jobs/kie/main/errai_pr.groovy

Errai Maven cmd still contain -Dfull property to activate FULL profile when it was part of FdB for other KIE projects.
<pre>
</pre>

removed -Dfull from Errai jobs

---

job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

**JIRA**: 
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1333
Fix jenkins job branch filtering in order to show the `main` branch for productized jobs [1].
Fix https://github.com/kiegroup/kie-jenkins-scripts/pull/1333
[1] https://kiegroup.github.io/droolsjbpm-build-bootstrap/job/productization-jobs
<pre>
</pre>

Show prod job main branch fixed

---

job-dsls/src/main/resources/job-scripts/prod_rhbop_trigger_umb_message.jenkinsfile

**JIRA**: 
- https://issues.redhat.com/browse/BXMSPROD-1863
Added build version information for the following projects:
- optaplanner-quickstarts
- optaweb-vehicle-routing
<pre>
</pre>

[RHBOP] Added version information for quickstarts and optaweb projects

---

job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile

etc. 
Remove kogito.nightly status for the following branches:
- `1.24.x`
- `1.27.x`
<pre>
</pre>

Removed kogito.nightly status for 1.24.x and 1.27.x

---

job-dsls/src/main/resources/job-scripts/prod_rhbop_trigger_umb_message.jenkinsfile

Reverts kiegroup/kie-jenkins-scripts#1353
As a result of https://gitlab.cee.redhat.com/middleware/build-configurations/-/merge_requests/965 we won't need to provide `quickstarts` and `optaweb` versions as they would be exactly the same as the `optaplanner` one.

Revert "[RHBOP] Added version information for quickstarts and optaweb projects"

---

job-dsls/jobs/kie/main/jbake_web_publishing.groovy

https://issues.redhat.com/browse/PLANNER-2855
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/685
- https://github.com/kiegroup/optaplanner/pull/2301
- https://github.com/kiegroup/optaplanner-website/pull/547
- https://github.com/kiegroup/kie-jenkins-scripts/pull/1360

Web publishing: Remove Optaplanner Website

---

job-dsls/jobs/prod/prod_rhpam_properties_generator.groovy

This property is not required
<pre>
</pre>

remove ERRAI_VERSION property from rhpam-properties-generator job

---

job-dsls/jobs/prod/prod_bamoe_kogito_stage_cpaas_artifacts.groovy
job-dsls/jobs/prod/prod_bamoe_stage_cpaas_artifacts.groovy
job-dsls/jobs/prod/prod_bamoe_staging.groovy
job-dsls/jobs/prod/prod_kogito_stage_cpaas_artifacts.groovy
job-dsls/jobs/prod/prod_rhba_stage_cpaas_artifacts.groovy
job-dsls/jobs/prod/prod_rhba_staging.groovy
job-dsls/jobs/prod/prod_rhbop_stage_cpaas_artifacts.groovy
job-dsls/src/main/resources/job-scripts/prod_bamoe_staging.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_staging.jenkinsfile

**JIRA**:
https://issues.redhat.com/browse/BXMSPROD-1926
* https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/202
Migrate to the new rcm-guest hostname `rcm-guest.hosts.prod.psi.bos.redhat.com`
Remove hardcoded usages of the rcm-guest host, using `RCM_HOST` env variable instead.
<pre>
</pre>

[BXMSPROD-1926] Upgrading to rcm-guest.hosts.prod.psi.bos.redhat.com

---

.ci/actions/backporting/action.yml
.ci/actions/build-chain/action.yml
.ci/actions/long-paths/action.yml
.ci/actions/maven/action.yml
.ci/actions/os-preparation/action.yml
.ci/actions/parse-labels/action.yml
.ci/actions/surefire-report/action.yml
.ci/actions/ubuntu-disk-space/action.yml
.github/workflows/pr-backporting.yml

**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1929
Centralize composite GitHub actions here, merging those from droolsjbpm-build-bootstrap and kogito-pipelines.
Differences from the original ones:
* **build-chain**:
* removed default `definition-file` as it depends on the final project structure, there is no default - this must be provided by any workflow using this action
* **maven**:
* made `Setup Maven Settings` optional since it is not needed in droolsjbpm-build-boostrap related projects, they will have to explicitly set `setup-maven-settings` to "false".
* **dsl-tests**:
* added new input `seed-repository` which defaults to `kiegroup/kogito-pipelines` but can be overridden to make the action much …

[BXMSPROD-1929] Centralize composite github actions

---

job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1949
Related to change applied for Optaplanner as part of Jira https://issues.redhat.com/browse/BXMSPROD-1945
- https://github.com/kiegroup/kogito-pipelines/pull/779
- https://github.com/kiegroup/kie-ci/pull/1413
<pre>
</pre>

[BXMSPROD-1949] Do not set next product version and drools version for OSL main

---

job-dsls/jobs/prod/prod_rhbop_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_rhbop_trigger_umb_message.jenkinsfile

Since Quarkus 2.13.x, core and platform artifacts could be different each other - for this reason we split versions in:
- `platform.quarkus.bom`
- `quarkus.bom` 
**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1960
etc. 
<pre>
</pre>

[BXMSPROD-1960] RHBOP: split quarkus core and platform version

---

job-dsls/build.gradle
job-dsls/jobs/kie/branch/deploy_jobs.groovy
job-dsls/jobs/kie/branch/deploy_jobs_7_x.groovy
job-dsls/jobs/kie/branch/errai_jdk8_pr.groovy
job-dsls/jobs/kie/branch/errai_pr.groovy
job-dsls/jobs/kie/branch/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/kie/branch/sonarcloud_daily.groovy
job-dsls/jobs/kie/branch/springboot_pr_job.groovy
job-dsls/jobs/kie/branch/turtleTests.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/BasicJob.groovy

In any DSL groovy script JOB_OWNER_EMAIL or JOB_COOWNERS_EMAIL are used
[BXMSPROD-1963](https://issues.redhat.com/browse/BXMSPROD-1963)
etc. 
<pre>
</pre>

[BXMSPROD-1963] Removed use of ownership plugin

---

job-dsls/build.gradle
job-dsls/jobs/kie/branch/deploy_jobs.groovy
job-dsls/jobs/kie/branch/kie_jenkinsScripts_PR.groovy
job-dsls/jobs/kie/branch/sonarcloud_daily.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/BasicJob.groovy

removed leftovers of ownership plugin on branch 7.67.x.
On `eng-jenkins` we don't have/use this plugin anymore - this is the reason why the seed job for 7.67.x fails.
* https://github.com/kiegroup/kie-ci/pull/1445
* https://github.com/kiegroup/kie-ci/pull/1446
<pre>
</pre>

removed ownership plugin dependencies

---

.ci/actions/backporting/action.yml

**JIRA**: [https://issues.redhat.com/browse/BXMSPROD-1930](https://issues.redhat.com/browse/BXMSPROD-1930)
**Referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2263
* https://github.com/kiegroup/kogito-pipelines/pull/935
* https://github.com/kiegroup/kie-ci/pull/1476
You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)
<details>
<summary>
How to replicate CI configuration locally?
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories …

[BXMSPROD-1930] Fixing/updating Backporting action.

---

.ci/actions/parse-labels/action.yml

**JIRA:** https://issues.redhat.com/browse/BXMSPROD-2064
**referenced Pull Requests:**
* https://github.com/kiegroup/kie-ci/pull/1514
* https://github.com/kiegroup/kogito-pipelines/pull/999
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2321
As suggested here: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable setting untrusted input as env variable
<pre>
</pre>

[BXMSPROD-2064] set untrusted input as intermediate env variable

---

job-dsls/jobs/prod/prod_bamoe_create_images_templates_and_sources.groovy
job-dsls/jobs/prod/prod_bamoe_kogito_create_images_sources.groovy
job-dsls/jobs/prod/prod_create_images_templates_and_sources.groovy
job-dsls/jobs/prod/prod_kogito_create_images_sources.groovy
job-dsls/src/main/resources/job-scripts/prod_bamoe_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_bamoe_kogito_create_images_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_create_images_sources.jenkinsfile

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2105
<pre>
</pre>

[BXMSPROD-2105] parametrize the OpenShift images branch used to build the images in jobs that create templates and sources

---

job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmContainerTestMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/JbpmTestCoverageMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieServerMatrix.groovy
job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/templates/additionalTests/KieWbTestMatrix.groovy

The additional tests for daily builds
- JbpmContainerTestMatrix
- JbpmTestCoverageMatrix
- KieServerMatrix
- KieWbTestMatrix
are executed as first for main && jdk11.
The first time when trying to download via **wget** the artifacts they are not cached.
All daily builds after this find the artifacts because they have been cached. The new **wget** parameters  will try it several times with hopefully enough time in between to resolve this.
etc. 
<pre>
How to retest a PR or trigger a …

wait for caching artifacts when uploading to Nexus

---

job-dsls/jobs/osbs/bamoe_osbs_seed_cloud_jobs.groovy
job-dsls/jobs/osbs/rhpam_osbs_seed_cloud_jobs.groovy

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2122
<pre>
</pre>

[BXMSPROD-2122] replace docker command by podman

---

job-dsls/jobs/prod/prod_sync_branches.groovy
job-dsls/src/main/resources/job-scripts/prod_sync_branches.jenkinsfile

This job allows to sync a specific branch from the a repository from a GH organization to another. For example. branch 1.45.x of kogito-runtimes project can be synced from apache to kiegroup organization
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-2121
<pre>
</pre>

[BXMSPROD-2121] add sync-branches job

---

job-dsls/jobs/kie/branch/deploy_jobs_7_x.groovy

i noticed that the job on 7.x is failing with deploying and as it is setup to fixed version it doesn't make sense to deploy anything.
I removed it from downstream repositories to deploy
it will not generate this job path anymore /KIE/job/7.x/job/deployedRep/job/optaplanner-7.x/
<pre>
</pre>

Drop optaplanner 7.x branch from deploy jobs

---

job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

Without this fix, if an image was not built for the release, the value would be empty,
e.g: "operator":,"operator-bundle" ...
The correct way should be:
"operator":"","operator-bundle" ...
<pre>
</pre>

osl-trigger-umb-message: do not break UMB format if an image is missing to be build for the release

---

.ci/actions/main-sync/action.yml

**Jira:** https://issues.redhat.com/browse/SRVLOGIC-282
**Description:**
Move main-sync CI to kie-ci repository to make it reusable from other midstream repositories
- https://github.com/kiegroup/kogito-examples/pull/21
- https://github.com/kiegroup/kogito-runtimes/pull/33
- https://github.com/kiegroup/kogito-apps/pull/21
- https://github.com/kiegroup/drools/pull/46
- https://github.com/kiegroup/kogito-images/pull/34
- https://github.com/kiegroup/kogito-serverless-operator/pull/31
- https://github.com/kiegroup/kie-tools/pull/6

SRVLOGIC-282: Move main-sync CI to kie-ci repository

---

job-dsls/jobs/prod/prod_rhsa_errata_content.groovy
job-dsls/src/main/resources/job-scripts/prod_rhsa_errata_content.jenkinsfile

Depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/329
<pre>
</pre>

allow to add extra CVE Jiras not part of current product/version in rhsa-errata-content job

---

job-dsls/jobs/osbs/kogito_osbs_build_pipeline.jenkinsfile
job-dsls/jobs/osbs/osbs_build_pipeline.jenkinsfile
job-dsls/jobs/prod/prod_cron_meta_nightly_pipeline.groovy
job-dsls/jobs/prod/prod_cron_meta_nightly_rhpam_pipeline.groovy
job-dsls/jobs/prod/prod_replace_shared_libraries.groovy
job-dsls/jobs/prod/prod_rhba_prod_branch.groovy
job-dsls/jobs/prod/prod_rhba_replace_version.groovy
job-dsls/jobs/prod/prod_shared_libraries_new_branch.groovy
job-dsls/jobs/seed_jobs/kie_seed_job.groovy
job-dsls/jobs/seed_jobs/kie_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/kogito_tools_seed_job.groovy
job-dsls/jobs/seed_jobs/osbs_seed_job.groovy
job-dsls/jobs/seed_jobs/prod_seed_job.groovy
job-dsls/src/main/resources/job-scripts/generate_status_page_data.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_bamoe_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_bamoe_kogito_create_images_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_bamoe_kogito_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_bamoe_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_bamoe_staging.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_create_images_templates_and_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_create_release_trackers.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_create_images_sources.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_kogito_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhba_staging.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhbop_stage_cpaas_artifacts.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhbop_trigger_umb_message.jenkinsfile
job-dsls/src/main/resources/job-scripts/prod_rhsa_errata_content.jenkinsfile

[BXMSPROD-2209] move productization jobs and seed jobs to use rhel8

---

job-dsls/jobs/prod/prod_osl_trigger_umb_message.groovy
job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

Jira: https://issues.redhat.com/browse/BXMSPROD-2210
<pre>
</pre>

[BXMSPROD-2210] add Kn Workflow plugin binary as part of OSL prod UMB message

---

job-dsls/src/main/resources/job-scripts/prod_osl_trigger_umb_message.jenkinsfile

Print the images registries in the same format that is expected as part of the promotion email to make it easier.

print images registries as part of OSL prod UMB message job
